/**
 * Booting the appliance: the host half of one guest step.
 *
 * Frame the step script onto a payload disk, boot the appliance with the
 * target attached, read the framed status record back. The interesting part is
 * everything that is deliberately *not* here — no `-serial stdio`, no
 * positional disk names, no shared scratch directory — because each of those
 * is a way for a run to produce a plausible answer that belongs to a different
 * boot.
 *
 * @module
 */

import {
  CommandAbortedError,
  type CommandRunner,
  DenoCommandRunner,
} from "../runner.ts";
import {
  framePayload,
  parseStatus,
  STATUS_BYTES,
  type StepOutcome,
} from "./abi.ts";
import { APPLIANCE_ABI } from "./abi.ts";
import { DISK_SERIALS, diskArgs, type DiskAttachment } from "./devices.ts";
import type { ApplianceIdentity } from "./identity.ts";
import { GuestNetworkUnavailableError } from "./errors.ts";

/** What a guest layer needs run. */
export interface GuestStepRequest {
  /** The planned step's id, used in diagnostics only. */
  readonly stepId: string;
  /** The `.partial` overlay for THIS layer, opened READ-WRITE. Never a published parent. */
  readonly imagePath: string;
  /** Generated by {@link ./script.ts}. */
  readonly script: string;
  /** From `stepNonce(realizationKey, stepId)`. */
  readonly nonce: string;
  /** Scratch dir for payload/status/console — the layer's own `.partial`, never shared. */
  readonly scratchDir: string;
  /** A ustar blob attached as the `data` disk. */
  readonly data?: Uint8Array;
  /** The step declared `network: true`. */
  readonly network?: boolean;
  /** Logical sector size of the target. @default 512 */
  readonly sectorSize?: 512 | 4096;
}

/** What one guest step produced. */
export interface GuestStepResult {
  /** The status record the guest wrote and fsynced. */
  readonly outcome: StepOutcome;
  /** Everything the guest wrote to the serial console. */
  readonly console: string;
  /** Wall time from spawn to exit. */
  readonly elapsedMs: number;
}

/** The seam `build()` dispatches guest layers through. Fakeable in tests. */
export interface GuestRunner {
  /** Run one step in a guest and report what it did. */
  run(request: GuestStepRequest): Promise<GuestStepResult>;
}

/** How to reach the network from inside a guest step. */
export interface GuestNetworkOptions {
  /** Resolver address written to the guest's `/etc/resolv.conf`. */
  readonly dns: string;
}

/** Construction options for {@linkcode ApplianceGuestRunner}. */
export interface ApplianceOptions {
  /** The verified appliance, from `readApplianceIdentity()`. */
  readonly identity: ApplianceIdentity;
  /** Root holding `<arch>/`. @default ".appliance" */
  readonly root?: string;
  /** Subprocess seam. @default a real `DenoCommandRunner` */
  readonly runner?: CommandRunner;
  /** Boot deadline. @default 120_000 native, 600_000 cross-arch */
  readonly timeoutMs?: number;
  /**
   * Enable `run({ network: true })`. Slirp's own resolver at 10.0.2.3 never
   * answers on qemu 11.0.2/macOS, and DHCP is impossible (no af_packet
   * module), so a resolver must be named explicitly. Omit and a networked step
   * is refused rather than run unplugged.
   */
  readonly network?: GuestNetworkOptions;
  /**
   * Claim a different `qi.abi` on the kernel cmdline.
   *
   * Exists so the wire tripwire can be **proved** rather than asserted: a boot
   * with `abi: 99` must come back as stage `"abi"`, rc 97. It cannot bypass
   * anything — the guest accepts exactly {@linkcode APPLIANCE_ABI} and refuses
   * every other value, and the host-side identity check has already run by the
   * time a runner exists. @default APPLIANCE_ABI
   */
  readonly abi?: number;
}

/** Guest console device per architecture, matching `appliance.lock.json`. */
const CONSOLE: Readonly<Record<string, string>> = {
  aarch64: "ttyAMA0",
  x86_64: "ttyS0",
};

/** Boots the real appliance under `qemu-system-<arch>`. */
export class ApplianceGuestRunner implements GuestRunner {
  readonly #identity: ApplianceIdentity;
  readonly #root: string;
  readonly #runner: CommandRunner;
  readonly #timeoutMs: number;
  readonly #network: GuestNetworkOptions | undefined;
  readonly #abi: number;

  /** Create a runner over an already-verified appliance identity. */
  constructor(options: ApplianceOptions) {
    this.#identity = options.identity;
    this.#root = options.root ?? ".appliance";
    this.#runner = options.runner ?? new DenoCommandRunner();
    // A same-arch guest accelerates; a cross-arch guest is emulated end to end
    // and is roughly an order of magnitude slower, so it gets a longer
    // deadline rather than a shared one that is wrong for both.
    const native = options.identity.arch === Deno.build.arch;
    this.#timeoutMs = options.timeoutMs ?? (native ? 120_000 : 600_000);
    this.#network = options.network;
    this.#abi = options.abi ?? APPLIANCE_ABI;
  }

  /** Boot the appliance, run one step, and return its status record. */
  async run(request: GuestStepRequest): Promise<GuestStepResult> {
    if (request.network === true && this.#network === undefined) {
      throw new GuestNetworkUnavailableError(request.stepId);
    }
    const arch = this.#identity.arch;
    const work = `${this.#root}/${arch}`;
    const scratch = request.scratchDir;

    // Every scratch file lives in the layer's own directory. Fixed paths under
    // a shared `run/` alias across concurrent builds, and `parseStatus` can
    // only tell a stale record from a fresh one by its nonce.
    const payloadPath = `${scratch}/payload.raw`;
    const statusPath = `${scratch}/status.raw`;
    const consolePath = `${scratch}/console.log`;
    const dataPath = `${scratch}/data.tar`;

    await Deno.writeFile(
      payloadPath,
      framePayload(request.script, { nonce: request.nonce }),
    );
    await Deno.writeFile(statusPath, new Uint8Array(STATUS_BYTES));
    if (request.data !== undefined) {
      await Deno.writeFile(dataPath, request.data);
    }

    const disks: DiskAttachment[] = [
      {
        role: "target",
        path: request.imagePath,
        format: "qcow2",
        ...(request.sectorSize === undefined
          ? {}
          : { sectorSize: request.sectorSize }),
      },
      { role: "payload", path: payloadPath, format: "raw" },
      { role: "status", path: statusPath, format: "raw" },
      ...(request.data === undefined
        ? []
        : [{ role: "data", path: dataPath, format: "raw" } as DiskAttachment]),
    ];

    const native = arch === Deno.build.arch;
    const accel = native ? (Deno.build.os === "darwin" ? "hvf" : "kvm") : "tcg";
    // Roles ride the cmdline as SERIAL TOKENS, never as /dev paths: a /dev
    // path is a position, and positions move the moment a disk is attached
    // with a different spelling.
    const append = [
      `console=${CONSOLE[arch] ?? "ttyS0"}`,
      `qi.abi=${this.#abi}`,
      `qi.nonce=${request.nonce}`,
      `qi.payload=${DISK_SERIALS.payload}`,
      `qi.status=${DISK_SERIALS.status}`,
      ...(request.data === undefined ? [] : [`qi.data=${DISK_SERIALS.data}`]),
      ...(request.network === true && this.#network !== undefined
        ? [`qi.dns=${this.#network.dns}`]
        : []),
    ].join(" ");

    const argv = [
      "-M",
      this.#identity.machine,
      "-accel",
      accel,
      ...(native ? ["-cpu", "host"] : []),
      "-m",
      "1024",
      "-kernel",
      `${work}/boot/vmlinuz-virt`,
      "-initrd",
      `${work}/appliance.cpio.gz`,
      "-append",
      append,
      ...disks.flatMap(diskArgs),
      "-nic",
      request.network === true ? "user,model=virtio-net-pci" : "none",
      "-display",
      "none",
      "-no-reboot",
      // The console goes to a FILE, never through a pipe: a captured pipe
      // stays open for as long as any descendant holds its write end, so the
      // deadline would race output rather than the guest.
      "-serial",
      `file:${consolePath}`,
    ];

    const started = Date.now();
    try {
      const result = await this.#runner.run(`qemu-system-${arch}`, argv, {
        timeoutMs: this.#timeoutMs,
        stdout: "null",
      });
      // A runner never throws on a nonzero exit, so without this the failure
      // falls through to `parseStatus` reading an all-zero status disk and
      // reports that the guest panicked or hung. It did not: it never booted,
      // and the one place that says why — qemu's own stderr — would be thrown
      // away. This is the one case where qemu's exit code IS the answer.
      if (result.code !== 0) {
        throw new Error(
          `qemu exited ${result.code} without booting the guest for step ` +
            `${request.stepId}. This is not a step failure — the VM never ` +
            `started:\n${result.stderr.trim() || "(no stderr)"}`,
        );
      }
    } catch (error) {
      if (error instanceof CommandAbortedError) {
        throw new Error(
          `guest step ${request.stepId} did not power off within ` +
            `${this.#timeoutMs}ms — it hung. qemu's exit code could not have ` +
            "told you that either: it exits 0 for a panic under -no-reboot " +
            `just as it does for a clean poweroff. Console: ${consolePath}`,
          { cause: error },
        );
      }
      throw error;
    }
    const elapsedMs = Date.now() - started;

    const consoleText = await Deno.readTextFile(consolePath).catch(() => "");
    const outcome = parseStatus(await Deno.readFile(statusPath), {
      nonce: request.nonce,
    });
    return { outcome, console: consoleText, elapsedMs };
  }
}
