/**
 * Booting the appliance: the host half of one guest step.
 *
 * Frame the step script onto a payload disk, boot the appliance with the
 * target attached, read the framed status record back. The interesting part is
 * everything that is deliberately *not* here — no `-serial stdio`, no
 * positional disk names, no shared scratch directory — because each of those
 * is a way for a run to produce a plausible answer that belongs to a different
 * boot.
 *
 * @module
 */

import {
  CommandAbortedError,
  type CommandRunner,
  DenoCommandRunner,
} from "../runner.ts";
import {
  framePayload,
  parseStatus,
  STATUS_BYTES,
  type StepOutcome,
} from "./abi.ts";
import { APPLIANCE_ABI } from "./abi.ts";
import { DISK_SERIALS, diskArgs, type DiskAttachment } from "./devices.ts";
import type { ApplianceIdentity } from "./identity.ts";
import {
  GuestBootError,
  GuestNetworkUnavailableError,
  GuestStatusError,
  GuestTimeoutError,
  InvalidGuestDnsError,
} from "./errors.ts";

/** What a guest layer needs run. */
export interface GuestStepRequest {
  /** The planned step's id, used in diagnostics only. */
  readonly stepId: string;
  /** The `.partial` overlay for THIS layer, opened READ-WRITE. Never a published parent. */
  readonly imagePath: string;
  /** Generated by {@link ./script.ts}. */
  readonly script: string;
  /** From `stepNonce(realizationKey, stepId)`. */
  readonly nonce: string;
  /** Scratch dir for payload/status/console — the layer's own `.partial`, never shared. */
  readonly scratchDir: string;
  /** A ustar blob attached as the `data` disk. */
  readonly data?: Uint8Array;
  /** The step declared `network: true`. */
  readonly network?: boolean;
  /** Logical sector size of the target. @default 512 */
  readonly sectorSize?: 512 | 4096;
  /**
   * Deadline for THIS step, overriding the runner's.
   *
   * Steps are not the same size. A 200 MiB mkfs finishes in ~250ms on a
   * native guest while an `apk add` over slirp is bounded by a download, and
   * one number cannot be right for both: set it for the slow step and a hung
   * fast one burns the whole deadline before anyone hears about it.
   * @default the runner's `timeoutMs`
   */
  readonly timeoutMs?: number;
}

/** What one guest step produced. */
export interface GuestStepResult {
  /** The status record the guest wrote and fsynced. */
  readonly outcome: StepOutcome;
  /** Everything the guest wrote to the serial console. */
  readonly console: string;
  /** Wall time from spawn to exit. */
  readonly elapsedMs: number;
}

/** The seam `build()` dispatches guest layers through. Fakeable in tests. */
export interface GuestRunner {
  /** Run one step in a guest and report what it did. */
  run(request: GuestStepRequest): Promise<GuestStepResult>;
}

/** How to reach the network from inside a guest step. */
export interface GuestNetworkOptions {
  /** Resolver address written to the guest's `/etc/resolv.conf`. */
  readonly dns: string;
}

/** Construction options for {@linkcode ApplianceGuestRunner}. */
export interface ApplianceOptions {
  /** The verified appliance, from `readApplianceIdentity()`. */
  readonly identity: ApplianceIdentity;
  /** Root holding `<arch>/`. @default ".appliance" */
  readonly root?: string;
  /** Subprocess seam. @default a real `DenoCommandRunner` */
  readonly runner?: CommandRunner;
  /**
   * Default boot deadline, overridable per step.
   *
   * @default 120_000 native, 600_000 cross-arch
   */
  readonly timeoutMs?: number;
  /**
   * Where a failed boot's console log is copied so it outlives the build.
   *
   * The console is written into the step's `scratchDir`, which is the layer's
   * `.partial` — and `build()` calls `store.abandon()` on failure, which
   * removes that directory. Without a copy every error naming the console
   * names a file that has already been deleted by the time anyone reads it.
   *
   * Written to only when a step fails, and never cleaned up — surviving the
   * build is the entire point, so the caller owns its lifetime.
   * @default a fresh `Deno.makeTempDir({ prefix: "qemu-img-console-" })`
   */
  readonly consoleDir?: string;
  /**
   * Enable `run({ network: true })`. Slirp's own resolver at 10.0.2.3 never
   * answers on qemu 11.0.2/macOS, and DHCP is impossible (no af_packet
   * module), so a resolver must be named explicitly. Omit and a networked step
   * is refused rather than run unplugged.
   */
  readonly network?: GuestNetworkOptions;
  /**
   * Claim a different `qi.abi` on the kernel cmdline.
   *
   * Exists so the wire tripwire can be **proved** rather than asserted: a boot
   * with `abi: 99` must come back as stage `"abi"`, rc 97. It cannot bypass
   * anything — the guest accepts exactly {@linkcode APPLIANCE_ABI} and refuses
   * every other value, and the host-side identity check has already run by the
   * time a runner exists. @default APPLIANCE_ABI
   */
  readonly abi?: number;
}

/** Guest console device per architecture, matching `appliance.lock.json`. */
const CONSOLE: Readonly<Record<string, string>> = {
  aarch64: "ttyAMA0",
  x86_64: "ttyS0",
};

/**
 * Dotted-quad IPv4, and nothing else.
 *
 * Deliberately not a general address parser. This value is interpolated into
 * the kernel cmdline, so the only shapes that can survive are ones with no
 * whitespace — and the only ones the guest can *reach* are IPv4, since it is
 * configured `10.0.2.15/24` with an IPv4 default route and no IPv6 address at
 * all. A leading zero is refused because `010` is octal to some resolvers and
 * decimal to others, and a resolver at the wrong address just never answers.
 */
const IPV4 = /^(?:(?:0|[1-9]\d{0,2})\.){3}(?:0|[1-9]\d{0,2})$/;

/** Whether `value` is a dotted-quad IPv4 address with every octet in range. */
function isIpv4(value: string): boolean {
  if (!IPV4.test(value)) return false;
  return value.split(".").every((octet) => Number(octet) <= 255);
}

/** Boots the real appliance under `qemu-system-<arch>`. */
export class ApplianceGuestRunner implements GuestRunner {
  readonly #identity: ApplianceIdentity;
  readonly #root: string;
  readonly #runner: CommandRunner;
  readonly #timeoutMs: number;
  readonly #network: GuestNetworkOptions | undefined;
  readonly #abi: number;
  readonly #consoleDir: string | undefined;
  /** Created on first use, so a run that never fails never makes a directory. */
  #consoleDirPromise: Promise<string> | undefined;

  /** Create a runner over an already-verified appliance identity. */
  constructor(options: ApplianceOptions) {
    this.#identity = options.identity;
    this.#root = options.root ?? ".appliance";
    this.#runner = options.runner ?? new DenoCommandRunner();
    // Validated HERE, not at run time: the value rides the kernel cmdline
    // beside the nonce, which has always been validated, and a `dns` carrying
    // a space does not fail — it silently changes the arguments the guest
    // parses. Failing at construction means it cannot reach a boot at all.
    if (options.network !== undefined && !isIpv4(options.network.dns)) {
      throw new InvalidGuestDnsError(options.network.dns);
    }
    // A same-arch guest accelerates; a cross-arch guest is emulated end to end
    // and is roughly an order of magnitude slower, so it gets a longer
    // deadline rather than a shared one that is wrong for both.
    const native = options.identity.arch === Deno.build.arch;
    this.#timeoutMs = options.timeoutMs ?? (native ? 120_000 : 600_000);
    this.#network = options.network;
    this.#abi = options.abi ?? APPLIANCE_ABI;
    this.#consoleDir = options.consoleDir;
  }

  /**
   * Copy the console somewhere `store.abandon()` cannot reach, and read it.
   *
   * Best effort by construction: this runs only on paths that are already
   * failing, and a retention error must never replace the failure that caused
   * it. A `undefined` path means the copy did not happen — the text is still
   * returned, and it is still embedded in the error.
   */
  async #retainConsole(
    stepId: string,
    consolePath: string,
  ): Promise<{ text: string; retained: string | undefined }> {
    const text = await Deno.readTextFile(consolePath).catch(() => "");
    try {
      if (this.#consoleDirPromise === undefined) {
        const configured = this.#consoleDir;
        const pending = configured === undefined
          ? Deno.makeTempDir({ prefix: "qemu-img-console-" })
          : Deno.mkdir(configured, { recursive: true }).then(() => configured);
        // Forget a rejection rather than caching it: one full disk must not
        // stop every later step from retaining its console.
        pending.catch(() => {
          this.#consoleDirPromise = undefined;
        });
        this.#consoleDirPromise = pending;
      }
      const dir = await this.#consoleDirPromise;
      // The step id reaches a filename, so anything that is not obviously
      // safe in one is replaced: ids carry `:` (`table:mkfs`) by design.
      const stem = stepId.replaceAll(/[^A-Za-z0-9._-]/g, "_") || "step";
      const retained = `${dir}/${stem}-console.log`;
      await Deno.writeTextFile(retained, text);
      return { text, retained };
    } catch {
      return { text, retained: undefined };
    }
  }

  /** Boot the appliance, run one step, and return its status record. */
  async run(request: GuestStepRequest): Promise<GuestStepResult> {
    if (request.network === true && this.#network === undefined) {
      throw new GuestNetworkUnavailableError(request.stepId);
    }
    const arch = this.#identity.arch;
    const work = `${this.#root}/${arch}`;
    const scratch = request.scratchDir;

    // Every scratch file lives in the layer's own directory. Fixed paths under
    // a shared `run/` alias across concurrent builds, and `parseStatus` can
    // only tell a stale record from a fresh one by its nonce.
    const payloadPath = `${scratch}/payload.raw`;
    const statusPath = `${scratch}/status.raw`;
    const consolePath = `${scratch}/console.log`;
    const dataPath = `${scratch}/data.tar`;

    await Deno.writeFile(
      payloadPath,
      framePayload(request.script, { nonce: request.nonce }),
    );
    await Deno.writeFile(statusPath, new Uint8Array(STATUS_BYTES));
    if (request.data !== undefined) {
      await Deno.writeFile(dataPath, request.data);
    }

    const disks: DiskAttachment[] = [
      {
        role: "target",
        path: request.imagePath,
        format: "qcow2",
        ...(request.sectorSize === undefined
          ? {}
          : { sectorSize: request.sectorSize }),
      },
      { role: "payload", path: payloadPath, format: "raw" },
      { role: "status", path: statusPath, format: "raw" },
      ...(request.data === undefined
        ? []
        : [{ role: "data", path: dataPath, format: "raw" } as DiskAttachment]),
    ];

    const native = arch === Deno.build.arch;
    const accel = native ? (Deno.build.os === "darwin" ? "hvf" : "kvm") : "tcg";
    // Roles ride the cmdline as SERIAL TOKENS, never as /dev paths: a /dev
    // path is a position, and positions move the moment a disk is attached
    // with a different spelling.
    const append = [
      `console=${CONSOLE[arch] ?? "ttyS0"}`,
      `qi.abi=${this.#abi}`,
      `qi.nonce=${request.nonce}`,
      `qi.payload=${DISK_SERIALS.payload}`,
      `qi.status=${DISK_SERIALS.status}`,
      ...(request.data === undefined ? [] : [`qi.data=${DISK_SERIALS.data}`]),
      ...(request.network === true && this.#network !== undefined
        ? [`qi.dns=${this.#network.dns}`]
        : []),
    ].join(" ");

    const argv = [
      "-M",
      this.#identity.machine,
      "-accel",
      accel,
      ...(native ? ["-cpu", "host"] : []),
      "-m",
      "1024",
      "-kernel",
      `${work}/boot/vmlinuz-virt`,
      "-initrd",
      `${work}/appliance.cpio.gz`,
      "-append",
      append,
      ...disks.flatMap(diskArgs),
      "-nic",
      request.network === true ? "user,model=virtio-net-pci" : "none",
      "-display",
      "none",
      "-no-reboot",
      // The console goes to a FILE, never through a pipe: a captured pipe
      // stays open for as long as any descendant holds its write end, so the
      // deadline would race output rather than the guest.
      "-serial",
      `file:${consolePath}`,
    ];

    const started = Date.now();
    const timeoutMs = request.timeoutMs ?? this.#timeoutMs;
    try {
      const result = await this.#runner.run(`qemu-system-${arch}`, argv, {
        timeoutMs,
        stdout: "null",
      });
      // A runner never throws on a nonzero exit, so without this the failure
      // falls through to `parseStatus` reading an all-zero status disk and
      // reports that the guest panicked or hung. It did not: it never booted,
      // and the one place that says why — qemu's own stderr — would be thrown
      // away. This is the one case where qemu's exit code IS the answer.
      if (result.code !== 0) {
        throw new GuestBootError(
          request.stepId,
          result.code,
          result.stderr,
          `qemu exited ${result.code} without booting the guest for step ` +
            `${request.stepId}. This is not a step failure — the VM never ` +
            `started:\n${result.stderr.trim() || "(no stderr)"}`,
        );
      }
    } catch (error) {
      if (error instanceof CommandAbortedError) {
        const { text, retained } = await this.#retainConsole(
          request.stepId,
          consolePath,
        );
        throw new GuestTimeoutError(
          request.stepId,
          timeoutMs,
          text,
          retained,
          error,
        );
      }
      throw error;
    }
    const elapsedMs = Date.now() - started;

    const consoleText = await Deno.readTextFile(consolePath).catch(() => "");
    const statusBytes = await Deno.readFile(statusPath).catch(
      () => new Uint8Array(STATUS_BYTES),
    );
    let outcome: StepOutcome;
    try {
      outcome = parseStatus(statusBytes, { nonce: request.nonce });
    } catch (error) {
      if (!(error instanceof GuestStatusError)) throw error;
      // Until this existed the console was read one line above and dropped on
      // the floor right here — in the exact case where the record says
      // nothing, so the console is the only account of the boot. One of these
      // faults cannot produce a record at all: an `/init` that resolves its
      // status role to zero disks has nowhere to write one, and explains
      // itself on the console and nowhere else.
      const { text, retained } = await this.#retainConsole(
        request.stepId,
        consolePath,
      );
      throw new GuestStatusError(error.fault, error.reason, {
        ...(error.field === undefined ? {} : { field: error.field }),
        console: text,
        ...(retained === undefined ? {} : { consolePath: retained }),
      });
    }
    return { outcome, console: consoleText, elapsedMs };
  }
}
