/**
 * The generated step script: pure string builders, no I/O and no clock.
 *
 * Everything here is POSIX `ash`. The appliance has no `bash`, no coreutils,
 * no GNU `tar`, no `sfdisk`/`partx`/`parted` and no `mkfs.fat` — and none of
 * them are on the pinned ISO either, so "add a package" is not an escape
 * hatch. No arrays, no `[[ ]]`, no process substitution.
 *
 * `/init` prepends `set -eu` to whatever these produce, because without it
 * `$?` is the LAST command's status and `mke2fs …; sync` would report sync's
 * zero over a failed format. That does **not** cover pipelines — see the
 * README's guest-tier hazard table.
 *
 * @module
 */

/** One partition the guest must format. */
export interface MkfsPartition {
  /** 1-based GPT partition number; the node is `${target}${number}`. */
  readonly number: number;
  /** Partition start, in 512-byte sysfs sectors: `firstLba * sectorSize / 512`. */
  readonly startSectors512: number;
  /** Partition length, in 512-byte sysfs sectors: `lengthBytes / 512`. */
  readonly sizeSectors512: number;
  /** ext4 volume label (NOT the GPT partition name). */
  readonly fsLabel: string;
  /** Filesystem UUID, derived from `determinism.fsSeed`. */
  readonly uuid: string;
  /** `-E hash_seed=`, derived from `determinism.fsSeed`. */
  readonly hashSeed: string;
}

/** Arguments to {@linkcode mkfsScript}. */
export interface MkfsScriptArgs {
  /**
   * `E2FSPROGS_FAKE_TIME`, in seconds.
   *
   * The only *measured*-working time pin on this e2fsprogs build. Two runs
   * five seconds apart with `-U` and `hash_seed` but no fake time produced
   * different bytes; adding it made two separate boots byte-identical.
   * `SOURCE_DATE_EPOCH` on this build is **unmeasured**.
   */
  readonly fakeTimeEpoch: number;
  /** The partitions to format, in the order they should be formatted. */
  readonly partitions: readonly MkfsPartition[];
}

/** Arguments to {@linkcode copyInScript}. */
export interface CopyInScriptArgs {
  /** 1-based GPT partition number holding the root filesystem. */
  readonly rootPartitionNumber: number;
  /** Destination inside the image: absolute, normalized, `/`-separated. */
  readonly to: string;
}

/** Arguments to {@linkcode runScript}. */
export interface RunScriptArgs {
  /** 1-based GPT partition number holding the root filesystem. */
  readonly rootPartitionNumber: number;
  /** The author's script, emitted verbatim. */
  readonly script: string;
}

/**
 * Format each partition. Never mounts; never populates.
 *
 * The sysfs start/size cross-check is the load-bearing part. `mke2fs` formats
 * whatever device it is handed, and the kernel's own parse of the GPT the
 * previous layer just wrote is the **one statement of partition location that
 * shares no code with `src/fs/gpt.ts`**. Comparing it before formatting turns
 * a plan/GPT disagreement into exit 65/66 instead of a correct-looking ext4 in
 * the wrong window.
 *
 * Formatting the partition node — never `mke2fs -E offset=` — also makes the
 * kernel enforce the end: a 200 MiB `dd` into a 128 MiB partition stopped at
 * exactly 134217728 bytes. The offset path was measured to produce, on a
 * one-block arithmetic error, a filesystem `blkid` calls ext4 and the kernel
 * then refuses to mount. That is the silent-corruption shape this package
 * refuses.
 */
export function mkfsScript(args: MkfsScriptArgs): string {
  if (args.partitions.length === 0) {
    throw new Error(
      "mkfsScript was given no partitions. An empty mkfs layer would publish " +
        "as a successful format of nothing, and every descendant would mount " +
        "a filesystem that was never created. Emit the layer only when " +
        "there is a kernel filesystem to make.",
    );
  }
  const lines = [
    "# --- generated by src/system/script.ts: mkfs ---",
    ...PART_HELPER,
    "QI_NAME=${QI_TARGET#/dev/}",
  ];
  for (const partition of args.partitions) {
    const node = `"\${QI_TARGET}${partition.number}"`;
    const sysfs = `"\${QI_NAME}${partition.number}"`;
    lines.push(
      "",
      `qi_part ${node} ${sysfs} ${partition.startSectors512} ` +
        `${partition.sizeSectors512}`,
      // All four determinism knobs are load-bearing and measured: dropping
      // `hash_seed` left 100 differing bytes, dropping `-U` left 558. `-b 4096`
      // is mandatory because mke2fs picks its block size from DEVICE SIZE —
      // 1024 on a 64 MiB device, 4096 on a 1 GiB one — so without it growing a
      // partition silently relays out the filesystem.
      `E2FSPROGS_FAKE_TIME=${args.fakeTimeEpoch} mke2fs -t ext4 -F -q -b 4096 \\`,
      `  -L ${shellQuote(partition.fsLabel)} \\`,
      `  -U ${partition.uuid} \\`,
      `  -E hash_seed=${partition.hashSeed},nodiscard,root_owner=0:0 \\`,
      `  ${node}`,
      // /init's epilogue runs `e2fsck -fn` over every device listed here,
      // after every unmount, and its rc rides in the status frame.
      `echo ${node} >> /qi/fsck-devs`,
    );
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Mount the root partition and extract the data disk's tar under `to`.
 *
 * busybox `tar` reads the raw block device directly. The archive's two
 * all-zero-block trailer is self-delimiting, so there is no `dd |` stage and
 * no length header — a 3 MiB tar on a 1 GiB device extracted in ~0.86 s
 * without scanning the rest.
 */
export function copyInScript(args: CopyInScriptArgs): string {
  const node = `"\${QI_TARGET}${args.rootPartitionNumber}"`;
  return [
    "# --- generated by src/system/script.ts: copyIn ---",
    ...MOUNT_HELPER,
    // A missing data disk is a host bug, and without this check `tar -xf ""`
    // would fail with an error naming the empty string rather than the cause.
    '[ -n "${QI_DATA:-}" ] || { echo "qi: copyIn with no data disk attached"; ' +
    "exit 67; }",
    `qi_mount_root ${node}`,
    `mkdir -p ${
      shellQuote(args.to === "/" ? "/mnt/root" : `/mnt/root${args.to}`)
    }`,
    // No -m (mtimes come from the archive, which the writer pins), no -o (the
    // writer already emits uid/gid 0), and no --numeric-owner /
    // --strip-components / --xattrs — busybox tar has none of them.
    `tar -xf "$QI_DATA" -C ${
      shellQuote(args.to === "/" ? "/mnt/root" : `/mnt/root${args.to}`)
    }`,
    "",
  ].join("\n");
}

/**
 * Mount the root partition and run the author's script with `$QI_ROOT` set.
 *
 * The unmount is `/init`'s epilogue, so it runs even when the author's script
 * fails. This deliberately does **not** `chroot`: a chroot into a freshly
 * built root fails with `chroot: can't execute '/bin/busybox': No such file or
 * directory`, which names the binary rather than the missing
 * `/lib/ld-musl-<arch>.so.1` that actually caused it. That message will be
 * misdiagnosed as "busybox didn't copy" every single time.
 */
export function runScript(args: RunScriptArgs): string {
  const node = `"\${QI_TARGET}${args.rootPartitionNumber}"`;
  return [
    "# --- generated by src/system/script.ts: run ---",
    ...MOUNT_HELPER,
    `qi_mount_root ${node}`,
    "QI_ROOT=/mnt/root",
    "export QI_ROOT",
    'cd "$QI_ROOT"',
    args.script.replace(/\n+$/, ""),
    "",
  ].join("\n");
}

/**
 * Wait for a partition node, then check it against the plan before touching it.
 *
 * sysfs `start` and `size` are **always** in 512-byte units regardless of the
 * device's logical block size, which is why the caller converts rather than
 * passing LBAs through.
 */
const PART_HELPER: readonly string[] = [
  "qi_part() {",
  "  # $1 device  $2 sysfs name  $3 start (512B sectors)  $4 size (512B sectors)",
  "  i=0",
  '  while [ ! -b "$1" ] && [ "$i" -lt 50 ]; do mdev -s 2>/dev/null || true; ' +
  "sleep 0.1; i=$((i+1)); done",
  '  [ -b "$1" ] || { echo "qi: $1 never appeared — the kernel did not parse ' +
  'the GPT this build wrote"; exit 64; }',
  '  s=$(cat "/sys/class/block/$2/start"); n=$(cat "/sys/class/block/$2/size")',
  '  [ "$s" = "$3" ] || { echo "qi: $1 starts at sector $s; the plan says $3"; ' +
  "exit 65; }",
  '  [ "$n" = "$4" ] || { echo "qi: $1 is $n sectors; the plan says $4"; ' +
  "exit 66; }",
  "}",
];

/**
 * Mount the target's root filesystem once, idempotently, and register it for
 * the epilogue's `e2fsck`.
 *
 * `-t ext4` is not optional: busybox `mount` cannot autodetect ext4 in this
 * initramfs, and a bare `mount <dev>` fails with "No such file or directory"
 * (rc 255) on a perfectly good filesystem.
 */
const MOUNT_HELPER: readonly string[] = [
  "qi_mount_root() {",
  "  mkdir -p /mnt/root",
  "  mountpoint -q /mnt/root && return 0",
  '  grep -qx "$1" /qi/fsck-devs || echo "$1" >> /qi/fsck-devs',
  '  mount -t ext4 "$1" /mnt/root',
  "}",
];

/** Single-quote a value for `ash`, closing and reopening around each quote. */
function shellQuote(value: string): string {
  if (value.includes("\0")) {
    throw new Error(
      `${JSON.stringify(value)} holds a NUL byte, which cannot survive an ` +
        "argv. The generated script would silently truncate at it.",
    );
  }
  return `'${value.replaceAll("'", `'\\''`)}'`;
}
