/**
 * The generated step script: pure string builders, no I/O and no clock.
 *
 * Everything here is POSIX `ash`. The appliance has no `bash`, no coreutils,
 * no GNU `tar`, no `sfdisk`/`partx`/`parted` and no `mkfs.fat` — and none of
 * them are on the pinned ISO either, so "add a package" is not an escape
 * hatch. No arrays, no `[[ ]]`, no process substitution.
 *
 * `/init` prepends `set -eu` to whatever these produce, because without it
 * `$?` is the LAST command's status and `mke2fs …; sync` would report sync's
 * zero over a failed format. That does **not** cover pipelines — see the
 * README's guest-tier hazard table.
 *
 * Exit codes raised by generated scripts, chosen not to collide with `/init`'s
 * own `90`–`101`: `64` a declared partition node never appeared, `65`/`66` its
 * start/size disagree with the plan, `67` a `copyIn` with no data disk, `68`
 * the ROOT partition node never appeared, `69` the root partition holds no
 * filesystem `blkid` recognizes, `70` it holds one that is not ext2/3/4, `71`
 * the `copyIn` payload failed to extract.
 *
 * @module
 */

/** One partition the guest must format. */
export interface MkfsPartition {
  /** 1-based GPT partition number; the node is `${target}${number}`. */
  readonly number: number;
  /** Partition start, in 512-byte sysfs sectors: `firstLba * sectorSize / 512`. */
  readonly startSectors512: number;
  /** Partition length, in 512-byte sysfs sectors: `lengthBytes / 512`. */
  readonly sizeSectors512: number;
  /** ext4 volume label (NOT the GPT partition name). */
  readonly fsLabel: string;
  /** Filesystem UUID, derived from `determinism.fsSeed`. */
  readonly uuid: string;
  /** `-E hash_seed=`, derived from `determinism.fsSeed`. */
  readonly hashSeed: string;
}

/** Arguments to {@linkcode mkfsScript}. */
export interface MkfsScriptArgs {
  /**
   * `E2FSPROGS_FAKE_TIME`, in seconds.
   *
   * The only *measured*-working time pin on this e2fsprogs build. Two runs
   * five seconds apart with `-U` and `hash_seed` but no fake time produced
   * different bytes; adding it made two separate boots byte-identical.
   * `SOURCE_DATE_EPOCH` on this build is **unmeasured**.
   */
  readonly fakeTimeEpoch: number;
  /** The partitions to format, in the order they should be formatted. */
  readonly partitions: readonly MkfsPartition[];
}

/** Arguments to {@linkcode copyInScript}. */
export interface CopyInScriptArgs {
  /** 1-based GPT partition number holding the root filesystem. */
  readonly rootPartitionNumber: number;
  /** Destination inside the image: absolute, normalized, `/`-separated. */
  readonly to: string;
}

/** Arguments to {@linkcode runScript}. */
export interface RunScriptArgs {
  /** 1-based GPT partition number holding the root filesystem. */
  readonly rootPartitionNumber: number;
  /** The author's script, emitted verbatim. */
  readonly script: string;
}

/**
 * Format each partition. Never mounts; never populates.
 *
 * The sysfs start/size cross-check is the load-bearing part. `mke2fs` formats
 * whatever device it is handed, and the kernel's own parse of the GPT the
 * previous layer just wrote is the **one statement of partition location that
 * shares no code with `src/fs/gpt.ts`**. Comparing it before formatting turns
 * a plan/GPT disagreement into exit 65/66 instead of a correct-looking ext4 in
 * the wrong window.
 *
 * Formatting the partition node — never `mke2fs -E offset=` — also makes the
 * kernel enforce the end: a 200 MiB `dd` into a 128 MiB partition stopped at
 * exactly 134217728 bytes. The offset path was measured to produce, on a
 * one-block arithmetic error, a filesystem `blkid` calls ext4 and the kernel
 * then refuses to mount. That is the silent-corruption shape this package
 * refuses.
 */
export function mkfsScript(args: MkfsScriptArgs): string {
  if (args.partitions.length === 0) {
    throw new Error(
      "mkfsScript was given no partitions. An empty mkfs layer would publish " +
        "as a successful format of nothing, and every descendant would mount " +
        "a filesystem that was never created. Emit the layer only when " +
        "there is a kernel filesystem to make.",
    );
  }
  const lines = [
    "# --- generated by src/system/script.ts: mkfs ---",
    ...PART_HELPER,
    "QI_NAME=${QI_TARGET#/dev/}",
  ];
  for (const partition of args.partitions) {
    const node = `"\${QI_TARGET}${partition.number}"`;
    const sysfs = `"\${QI_NAME}${partition.number}"`;
    lines.push(
      "",
      `qi_part ${node} ${sysfs} ${partition.startSectors512} ` +
        `${partition.sizeSectors512}`,
      // All four determinism knobs are load-bearing and measured: dropping
      // `hash_seed` left 100 differing bytes, dropping `-U` left 558. `-b 4096`
      // is mandatory because mke2fs picks its block size from DEVICE SIZE —
      // 1024 on a 64 MiB device, 4096 on a 1 GiB one — so without it growing a
      // partition silently relays out the filesystem.
      `E2FSPROGS_FAKE_TIME=${args.fakeTimeEpoch} mke2fs -t ext4 -F -q -b 4096 \\`,
      `  -L ${shellQuote(partition.fsLabel)} \\`,
      `  -U ${partition.uuid} \\`,
      `  -E hash_seed=${partition.hashSeed},nodiscard,root_owner=0:0 \\`,
      `  ${node}`,
      // /init's epilogue runs `e2fsck -fn` over every device listed here,
      // after every unmount, and its rc rides in the status frame.
      `echo ${node} >> /qi/fsck-devs`,
    );
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Mount the root partition and extract the data disk's tar under `to`.
 *
 * busybox `tar` reads the raw block device directly. The archive's two
 * all-zero-block trailer is self-delimiting, so there is no `dd |` stage and
 * no length header — a 3 MiB tar on a 1 GiB device extracted in ~0.86 s
 * without scanning the rest.
 */
export function copyInScript(args: CopyInScriptArgs): string {
  const node = `"\${QI_TARGET}${args.rootPartitionNumber}"`;
  const dest = shellQuote(
    args.to === "/" ? "/mnt/root" : `/mnt/root${args.to}`,
  );
  return [
    "# --- generated by src/system/script.ts: copyIn ---",
    ...MOUNT_HELPER,
    // A missing data disk is a host bug, and without this check `tar -xf ""`
    // would fail with an error naming the empty string rather than the cause.
    '[ -n "${QI_DATA:-}" ] || { echo "qi: copyIn with no data disk attached"; ' +
    "exit 67; }",
    `qi_mount_root ${node} ${args.rootPartitionNumber}`,
    `mkdir -p ${dest}`,
    // No -m (mtimes come from the archive, which the writer pins), no -o (the
    // writer already emits uid/gid 0), and no --numeric-owner /
    // --strip-components / --xattrs — busybox tar has none of them.
    //
    // The `df` on failure is diagnosis, never a guard. Running out of room is
    // the likeliest way a copyIn into an EXISTING image fails — Alpine's
    // aarch64 cloud image ships its root 89% full, with about 35 MiB writable
    // as root — and busybox tar reports only `tar: write error: No space left
    // on device`, which does not say which filesystem or how full it was.
    // Measured: the step exits 1, `e2fsck` still passes, and the layer is
    // correctly never published. A *precheck* is deliberately not here: the
    // archive's byte count is not the space it occupies once ext4 rounds every
    // file up to a block, so a size comparison would refuse builds that fit.
    `if ! tar -xf "$QI_DATA" -C ${dest}; then`,
    '  echo "qi: extracting the copyIn payload failed. If the message above ' +
    "is ENOSPC, the image's root filesystem is full:\"",
    "  df -k /mnt/root || true",
    "  exit 71",
    "fi",
    "",
  ].join("\n");
}

/**
 * Mount the root partition and run the author's script with `$QI_ROOT` set.
 *
 * The unmount is `/init`'s epilogue, so it runs even when the author's script
 * fails. This deliberately does **not** `chroot`: a chroot into a freshly
 * built root fails with `chroot: can't execute '/bin/busybox': No such file or
 * directory`, which names the binary rather than the missing
 * `/lib/ld-musl-<arch>.so.1` that actually caused it. That message will be
 * misdiagnosed as "busybox didn't copy" every single time.
 */
export function runScript(args: RunScriptArgs): string {
  const node = `"\${QI_TARGET}${args.rootPartitionNumber}"`;
  return [
    "# --- generated by src/system/script.ts: run ---",
    ...MOUNT_HELPER,
    `qi_mount_root ${node} ${args.rootPartitionNumber}`,
    "QI_ROOT=/mnt/root",
    "export QI_ROOT",
    'cd "$QI_ROOT"',
    args.script.replace(/\n+$/, ""),
    "",
  ].join("\n");
}

/**
 * Wait for a partition node, then check it against the plan before touching it.
 *
 * sysfs `start` and `size` are **always** in 512-byte units regardless of the
 * device's logical block size, which is why the caller converts rather than
 * passing LBAs through.
 */
const PART_HELPER: readonly string[] = [
  "qi_part() {",
  "  # $1 device  $2 sysfs name  $3 start (512B sectors)  $4 size (512B sectors)",
  "  i=0",
  '  while [ ! -b "$1" ] && [ "$i" -lt 50 ]; do mdev -s 2>/dev/null || true; ' +
  "sleep 0.1; i=$((i+1)); done",
  '  [ -b "$1" ] || { echo "qi: $1 never appeared — the kernel did not parse ' +
  'the GPT this build wrote"; exit 64; }',
  '  s=$(cat "/sys/class/block/$2/start"); n=$(cat "/sys/class/block/$2/size")',
  '  [ "$s" = "$3" ] || { echo "qi: $1 starts at sector $s; the plan says $3"; ' +
  "exit 65; }",
  '  [ "$n" = "$4" ] || { echo "qi: $1 is $n sectors; the plan says $4"; ' +
  "exit 66; }",
  "}",
];

/**
 * Mount the target's root filesystem once, idempotently, and register it for
 * the epilogue's `e2fsck`.
 *
 * `-t ext4` is not optional: busybox `mount` cannot autodetect ext4 in this
 * initramfs, and a bare `mount <dev>` fails with "No such file or directory"
 * (rc 255) on a perfectly good filesystem.
 *
 * The two preflight checks exist for `base.kind: "image"`. A recipe that
 * declares its own layout is checked by {@link PART_HELPER}, which compares the
 * kernel's parse of the GPT against the plan — but an existing image's table
 * was written by someone else, so there is no planned geometry to compare
 * against and `rootPartition` is a number the recipe author had to read off the
 * image. Both ways of getting it wrong were measured against Alpine's aarch64
 * cloud image:
 *
 * - A number with no partition (`3`) reached `mount: mounting /dev/vda3 on
 *   /mnt/root failed: No such file or directory`, which never mentions
 *   `rootPartition` nor says which numbers would have worked.
 * - The image's own ESP (`1`) is FAT. Registering the device for the epilogue
 *   *before* attempting the mount meant `e2fsck` ran on it too, so the failure
 *   arrived as `Invalid argument` followed by twelve lines of superblock
 *   recovery advice, with `contains a vfat file system` on the last one.
 *
 * Ordering is therefore load-bearing: `blkid` runs BEFORE `/qi/fsck-devs` is
 * touched, so a non-ext filesystem is never handed to `e2fsck`.
 *
 * `blkid` is PARSED, not queried. busybox 1.37.0's applet takes `[BLOCKDEV]...`
 * and nothing else — it **accepts `-s TYPE -o value` silently and prints the
 * whole line anyway**, so the util-linux spelling yields
 * `/dev/vda2: LABEL="/" UUID="…" TYPE="ext4"` where the caller expected
 * `ext4`, and a case arm matching `ext4` would then reject a perfectly good
 * root. It also exits `0` on a device holding no filesystem, printing nothing,
 * so the empty string is the signal and the exit status is not.
 *
 * `ext2` and `ext3` are accepted because the ext4 driver mounts them: measured
 * here, `mke2fs -t ext2` and `-t ext3` images both mounted under
 * `mount -t ext4` at rc 0 and appear in `/proc/mounts` as `ext4`.
 */
const MOUNT_HELPER: readonly string[] = [
  "qi_mount_root() {",
  "  # $1 device  $2 the recipe's declared 1-based partition number",
  "  i=0",
  '  while [ ! -b "$1" ] && [ "$i" -lt 50 ]; do mdev -s 2>/dev/null || true; ' +
  "sleep 0.1; i=$((i+1)); done",
  '  if [ ! -b "$1" ]; then',
  '    echo "qi: $1 never appeared, so partition $2 is not in this image."',
  '    echo "qi: the target disk offers: $(ls -d ' +
  "/sys/class/block/\${QI_TARGET#/dev/}[0-9]* 2>/dev/null | sed 's|.*/||' | " +
  "tr '\\n' ' ')\"",
  '    echo "qi: base.rootPartition is the 1-based GPT number the image ' +
  'already has, not an index this build chose."',
  "    exit 68",
  "  fi",
  // Greedy `.*` anchors to the LAST ` TYPE="` on the line, which is the
  // filesystem's own; a LABEL that merely contains the text cannot win.
  '  _t=$(blkid "$1" 2>/dev/null | sed -n ' +
  '\'s/.*[[:space:]]TYPE="\\([^"]*\\)".*/\\1/p\')',
  '  case "$_t" in',
  "    ext2|ext3|ext4) ;;",
  '    "")',
  '      echo "qi: blkid finds no filesystem at all on $1 (partition $2)."',
  '      echo "qi: an unformatted or unrecognized partition mounts nowhere; ' +
  'check base.rootPartition."',
  "      exit 69",
  "      ;;",
  "    *)",
  '      echo "qi: $1 (partition $2) holds $_t, not ext4."',
  '      echo "qi: run and copyIn steps mount the image root read-write, and ' +
  'this appliance carries e2fsprogs and no other filesystem tooling."',
  '      echo "qi: point base.rootPartition at the ext4 partition, or drop ' +
  'the step."',
  "      exit 70",
  "      ;;",
  "  esac",
  "  mkdir -p /mnt/root",
  // Safe under `set -e`: a failing left operand of `&&` does not exit the
  // shell. Measured in this appliance — `( set -e; false && echo x; echo y )`
  // printed `y` and returned 0.
  "  mountpoint -q /mnt/root && return 0",
  '  grep -qx "$1" /qi/fsck-devs || echo "$1" >> /qi/fsck-devs',
  '  mount -t ext4 "$1" /mnt/root',
  "}",
];

/** Single-quote a value for `ash`, closing and reopening around each quote. */
function shellQuote(value: string): string {
  if (value.includes("\0")) {
    throw new Error(
      `${JSON.stringify(value)} holds a NUL byte, which cannot survive an ` +
        "argv. The generated script would silently truncate at it.",
    );
  }
  return `'${value.replaceAll("'", `'\\''`)}'`;
}
