/**
 * `build()` — execute a {@linkcode Plan} as a chain of qcow2 overlays.
 *
 * Each layer is created backed by its parent and published into the
 * content-addressed store, so re-running a build after editing one step
 * rebuilds only from that step onward.
 *
 * Two mechanisms do all the work. `image` and `bytes` layers use `qemu-img`
 * alone: a `raw` node with `offset`/`size` is a *window* onto the layer, so a
 * partition table or a filesystem is spliced in without touching its
 * neighbours, and FAT comes from qemu's `vvfat` driver reading a host
 * directory. `guest` layers boot the build appliance.
 *
 * @module
 */

import { QemuImg } from "../qemu_img.ts";
import { buildGpt, deriveGuid, PARTITION_TYPE_GUIDS } from "../fs/gpt.ts";
import { type RealizationKey, realizationKey } from "./keys.ts";
import type { Plan, PlannedPartition, PlannedStep } from "./plan.ts";
import { LayerStore, type StoredLayer } from "./store.ts";
import { GuestExecutorUnavailableError } from "./errors.ts";
import type { ResolvedRecipe, Step } from "./types.ts";

/** vvfat's own MBR occupies the first 32256 bytes; a window past it is the
 * bare filesystem. */
const VVFAT_MBR_BYTES = 32256;

/** Options for {@linkcode build}. */
export interface BuildOptions {
  /** Where layers are cached. */
  readonly store: LayerStore;
  /** Destination for the final artifact. */
  readonly output: string;
  /** The driver. @default a new QemuImg */
  readonly qemu?: QemuImg;
  /** Skip the on-hit container digest check. @default false */
  readonly trustCache?: boolean;
  /** Scratch directory for generated byte blobs. @default alongside the store */
  readonly scratch?: string;
}

/** What a build produced. */
export interface Artifact {
  /** Path to the materialized image. */
  readonly path: string;
  /** The final layer's realization key. */
  readonly realizationKey: RealizationKey;
  /** Per-layer provenance, base first. */
  readonly layers: readonly StoredLayer[];
  /** Which layers were served from cache. */
  readonly cacheHits: readonly string[];
}

/** Map a recipe partition type to its spec GUID. */
function typeGuidFor(type: string, arch: string): string {
  if (type === "esp") return PARTITION_TYPE_GUIDS.esp;
  if (type === "linux-root") {
    return arch === "aarch64"
      ? PARTITION_TYPE_GUIDS["linux-root-aarch64"]
      : PARTITION_TYPE_GUIDS["linux-root-x86_64"];
  }
  return PARTITION_TYPE_GUIDS["linux-generic"];
}

/** A `raw` window onto a qcow2 layer, for splicing bytes into one partition. */
function window(imagePath: string, offset: number, size: number) {
  return {
    imageOpts: {
      driver: "raw",
      offset,
      size,
      file: {
        driver: "qcow2",
        file: { driver: "file", filename: imagePath },
      },
    },
  } as const;
}

/** Execute one `bytes` layer: the partition table, then each filesystem. */
async function runBytesLayer(
  qemu: QemuImg,
  imagePath: string,
  scratch: string,
  step: Extract<Step, { kind: "partition" }>,
  layout: readonly PlannedPartition[],
  resolved: ResolvedRecipe,
): Promise<void> {
  const { recipe } = resolved;
  const sectorSize = recipe.platform.sectorSize ?? 512;
  const diskSizeBytes = recipe.base.kind === "blank"
    ? recipe.base.sizeBytes
    : 0;

  const partitions = await Promise.all(layout.map(async (partition) => ({
    typeGuid: typeGuidFor(partition.type, recipe.platform.arch),
    uniqueGuid: await deriveGuid(
      recipe.determinism.guidSeed,
      `partition:${partition.label}`,
    ),
    firstLba: partition.firstLba,
    lastLba: partition.lastLba,
    name: partition.label,
  })));
  const gpt = buildGpt({
    diskSizeBytes,
    sectorSize,
    diskGuid: await deriveGuid(recipe.determinism.guidSeed, "disk"),
    partitions,
  });

  // Both halves are spliced through windows, so nothing outside the GPT's own
  // footprint is touched.
  const primaryBin = `${scratch}/gpt-primary.bin`;
  const backupBin = `${scratch}/gpt-backup.bin`;
  await Deno.writeFile(primaryBin, gpt.primary);
  await Deno.writeFile(backupBin, gpt.backup);
  await qemu.convert(primaryBin, window(imagePath, 0, gpt.primary.byteLength), {
    sourceFormat: "raw",
    noCreate: true,
    parallel: 1,
  });
  await qemu.convert(
    backupBin,
    window(imagePath, gpt.backupOffsetBytes, gpt.backup.byteLength),
    { sourceFormat: "raw", noCreate: true, parallel: 1 },
  );

  for (const [index, partition] of layout.entries()) {
    const contents = step.partitions[index].contents;
    if (contents.kind !== "fat") continue;
    // vvfat synthesizes the filesystem from the host directory; the `raw`
    // window at 32256 strips vvfat's own MBR, so the partition type byte is
    // ours rather than vvfat's 0x06.
    await qemu.convert(
      {
        imageOpts: {
          driver: "raw",
          offset: VVFAT_MBR_BYTES,
          size: partition.lengthBytes,
          file: {
            driver: "vvfat",
            dir: contents.from.path,
            "fat-type": contents.fatType,
            label: contents.label,
          },
        },
      },
      window(imagePath, partition.offsetBytes, partition.lengthBytes),
      { noCreate: true, parallel: 1 },
    );
  }
}

/**
 * Execute a plan, reusing cached layers.
 *
 * Refuses a plan that needs the guest appliance unless one is wired in — with
 * a typed error naming the requirement rather than silently skipping the step.
 */
export async function build(
  plan: Plan,
  resolved: ResolvedRecipe,
  options: BuildOptions,
): Promise<Artifact> {
  const qemu = options.qemu ?? new QemuImg();
  const store = options.store;
  const scratch = options.scratch ?? `${store.root}/scratch`;
  await Deno.mkdir(scratch, { recursive: true });
  await Deno.mkdir(`${store.root}/layers`, { recursive: true });

  const layers: StoredLayer[] = [];
  const cacheHits: string[] = [];
  let parent: StoredLayer | undefined;

  for (const step of plan.steps) {
    if (step.executor === "guest") {
      throw new GuestExecutorUnavailableError(
        step.id,
        "this step needs a Linux kernel (ext4 creation, or running target " +
          "ELF), which no host-side mechanism can provide",
      );
    }
    const key = await realizationKey(
      step.recipeKey,
      parent === undefined ? undefined : {
        realizationKey: parent.realizationKey,
        containerSha256: parent.containerSha256,
      },
    );

    const cached = step.cacheable
      ? await store.get(key, { trust: options.trustCache })
      : undefined;
    if (cached !== undefined) {
      cacheHits.push(step.id);
      layers.push(cached);
      parent = cached;
      continue;
    }

    const dir = await store.begin(key);
    const imagePath = `${dir}/image.qcow2`;
    if (parent === undefined) {
      const base = resolved.recipe.base;
      if (base.kind !== "blank") {
        throw new GuestExecutorUnavailableError(
          step.id,
          "building from an existing base image is not wired up yet",
        );
      }
      await qemu.create(imagePath, {
        format: "qcow2",
        size: base.sizeBytes,
        ...(base.options === undefined ? {} : { options: base.options }),
      });
    } else {
      // Relative, so the whole store stays relocatable — and resolvable from
      // the same-depth `.partial` sibling both before and after the rename.
      await qemu.create(imagePath, {
        format: "qcow2",
        backing: `../${parent.realizationKey}/image.qcow2`,
        backingFormat: "qcow2",
      });
    }

    if (step.executor === "bytes") {
      const declared = resolved.recipe.steps[step.index];
      if (declared?.kind === "partition" && plan.layout !== undefined) {
        await runBytesLayer(
          qemu,
          imagePath,
          scratch,
          declared,
          plan.layout,
          resolved,
        );
      }
    }

    const published = await store.publish(
      key,
      step.recipeKey,
      parent?.containerSha256,
    );
    layers.push(published);
    parent = published;
  }

  if (parent === undefined) throw new Error("plan produced no layers");
  // Materialize by flattening the chain, so the artifact stands alone.
  await qemu.convert(parent.path, options.output, {
    format: "qcow2",
    parallel: 1,
  });
  return {
    path: options.output,
    realizationKey: parent.realizationKey,
    layers,
    cacheHits,
  };
}

/** Re-export for callers wiring their own store. */
export { LayerStore };
export type { PlannedStep };
