/**
 * `build()` — execute a {@linkcode Plan} as a chain of qcow2 overlays.
 *
 * Each layer is created backed by its parent and published into the
 * content-addressed store, so re-running a build after editing one step
 * rebuilds only from that step onward.
 *
 * Two mechanisms do all the work. `image` and `bytes` layers use `qemu-img`
 * alone: a `raw` node with `offset`/`size` is a *window* onto the layer, so a
 * partition table or a filesystem is spliced in without touching its
 * neighbours, and FAT comes from qemu's `vvfat` driver reading a host
 * directory. `guest` layers boot the build appliance.
 *
 * @module
 */

import { QemuImg } from "../qemu_img.ts";
import { normalizeFatTimestamps } from "../fs/fat.ts";
import { buildGpt, deriveGuid, PARTITION_TYPE_GUIDS } from "../fs/gpt.ts";
import { buildTar, type TarEntry } from "../fs/tar.ts";
import {
  copyInScript,
  type GuestRunner,
  GuestStepFailedError,
  type MkfsPartition,
  mkfsScript,
  runScript,
  stepNonce,
} from "../system/mod.ts";
import { sha256Hex } from "../digest.ts";
import { contentDigest } from "./content.ts";
import { type RealizationKey, realizationKey } from "./keys.ts";
import {
  type Plan,
  type PlannedPartition,
  type PlannedStep,
  totalSizeBytes,
} from "./plan.ts";
import { LayerStore, type StoredLayer } from "./store.ts";
import {
  BaseImageSizeMismatchError,
  GuestExecutorUnavailableError,
} from "./errors.ts";
import { resolvedDir } from "./resolve.ts";
import type { DirInput, ResolvedInput, ResolvedRecipe, Step } from "./types.ts";

/** vvfat's own MBR occupies the first 32256 bytes; a window past it is the
 * bare filesystem. */
const VVFAT_MBR_BYTES = 32256;

/** Options for {@linkcode build}. */
export interface BuildOptions {
  /** Where layers are cached. */
  readonly store: LayerStore;
  /** Destination for the final artifact. */
  readonly output: string;
  /** The driver. @default a new QemuImg */
  readonly qemu?: QemuImg;
  /** Skip the on-hit container digest check. @default false */
  readonly trustCache?: boolean;
  /** Scratch directory for generated byte blobs. @default alongside the store */
  readonly scratch?: string;
  /**
   * Where `guest` layers run. Omit and a plan containing one is refused with
   * {@linkcode GuestExecutorUnavailableError} rather than skipped — but every
   * layer BEFORE it still builds, publishes and caches.
   */
  readonly guest?: GuestRunner;
}

/** What a build produced. */
export interface Artifact {
  /** Path to the materialized image. */
  readonly path: string;
  /** The final layer's realization key. */
  readonly realizationKey: RealizationKey;
  /** Per-layer provenance, base first. */
  readonly layers: readonly StoredLayer[];
  /**
   * The {@linkcode StoredLayer.realizationKey} of every layer served from
   * cache, so `layers` can actually be filtered by it:
   *
   * ```ts
   * import type { Artifact } from "@nullstyle/qemu-img/recipe";
   * declare const artifact: Artifact;
   * const hits = artifact.layers.filter((layer) =>
   *   artifact.cacheHits.includes(layer.realizationKey)
   * );
   * ```
   *
   * BREAKING in 0.3.0: this held `step.id` while being typed `readonly
   * string[]` and documented as naming layers, so the filter above compiled
   * and returned `[]` forever — the shape this package refuses everywhere
   * else. A step id is still recoverable: `StoredLayer.recipeKey` is the
   * `PlannedStep.recipeKey` the plan already carries.
   */
  readonly cacheHits: readonly RealizationKey[];
}

/** Map a recipe partition type to its spec GUID. */
function typeGuidFor(type: string, arch: string): string {
  if (type === "esp") return PARTITION_TYPE_GUIDS.esp;
  if (type === "linux-root") {
    return arch === "aarch64"
      ? PARTITION_TYPE_GUIDS["linux-root-aarch64"]
      : PARTITION_TYPE_GUIDS["linux-root-x86_64"];
  }
  return PARTITION_TYPE_GUIDS["linux-generic"];
}

/**
 * The epoch whose LOCAL rendering equals `epoch`'s UTC calendar time.
 *
 * qemu's vvfat renders every timestamp through `localtime_r` before packing it
 * into a FAT directory entry, and FAT stores local time with no offset field —
 * so the same `sourceDateEpoch` lands as a different calendar time, and
 * different bytes, on every host whose clock is not set to UTC. Measured on
 * qemu 11.0.2: the same pinned tree converted under `TZ=UTC` and
 * `TZ=Asia/Tokyo` differs in 75 bytes.
 *
 * Pre-shifting the host mtime by the host's own UTC offset cancels that, so
 * the entry records `sourceDateEpoch` read as UTC wherever it is built. The
 * one instant this cannot express is a local time inside a spring-forward gap,
 * which does not exist and which the `Date` constructor normalizes forward by
 * the gap's width; a recipe pinned there records an hour later on hosts in
 * that zone. That is strictly narrower than the every-zone-differs it
 * replaces, so it is documented rather than refused.
 */
function vvfatLocalEpoch(epoch: number): number {
  const utc = new Date(epoch * 1000);
  const local = new Date(
    utc.getUTCFullYear(),
    utc.getUTCMonth(),
    utc.getUTCDate(),
    utc.getUTCHours(),
    utc.getUTCMinutes(),
    utc.getUTCSeconds(),
    0,
  );
  return Math.floor(local.getTime() / 1000);
}

/** One live entry of a staging tree, with the path it is recorded under. */
interface LiveEntry {
  /** Path relative to the tree root, `/`-separated. */
  readonly path: string;
  /** Absolute path on the host. */
  readonly full: string;
  /** What the host says it is. */
  readonly info: Deno.FileInfo;
}

/** Walk a staging tree parents-first, in the resolver's byte-wise order. */
async function* liveEntries(
  root: string,
  prefix = "",
): AsyncGenerator<LiveEntry> {
  const children: Deno.DirEntry[] = [];
  for await (const child of Deno.readDir(`${root}/${prefix}`)) {
    children.push(child);
  }
  // Byte-wise, matching `walkTree()` in ./resolve.ts — a locale-aware sort
  // would make the order depend on the machine's collation settings.
  children.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const child of children) {
    const path = prefix === "" ? child.name : `${prefix}/${child.name}`;
    const full = `${root}/${path}`;
    const info = await Deno.lstat(full);
    yield { path, full, info };
    if (info.isDirectory && !info.isSymlink) yield* liveEntries(root, path);
  }
}

/**
 * Copy a FAT staging tree into `scratch`, verified against the digest the
 * resolver recorded, with every timestamp pinned.
 *
 * One copy fixes two defects, and both are cache-poisoning rather than
 * cosmetic.
 *
 * **The tree vvfat reads must be the tree the key names.** `qemu-img` opens
 * the staging directory at BUILD time, but the layer's realization key was
 * computed from the digest `resolveRecipe()` took earlier. Editing the tree
 * in between published the new bytes under the old tree's key — permanently,
 * because a later hit serves that layer without ever re-reading the tree.
 * Copying first and hashing the COPY closes the window rather than narrowing
 * it: vvfat reads bytes this function already checked against the manifest,
 * and nothing outside can reach them afterwards. This is the re-hash
 * {@linkcode tarOf} already does for `copyIn`, extended to the tree's SHAPE —
 * a tree that gained a file would otherwise be published without it, which is
 * the same silent shortfall from the other direction.
 *
 * **vvfat stamps the host's timestamps into every directory entry.** It reads
 * `st_mtime`, `st_atime` and `st_ctime` off each file and packs them into the
 * entry's write, access and creation fields; it takes no time option, so
 * `determinism.sourceDateEpoch` never reaches it. Measured against qemu
 * 11.0.2 on macOS-aarch64, over a two-file tree: re-staging identical content
 * moved 30 bytes, and moving the mtimes alone, the atimes alone, a
 * subdirectory's own mtime, or the root directory's own mtime each moved the
 * image on its own (28–33 bytes). Pinning mtime and atime on the copy — every
 * file, every directory, and the root — settles the write-time and
 * access-date fields for good.
 *
 * It does NOT settle `st_ctime`, and that limit is the kernel's rather than
 * this code's: no userspace call sets it, and `utimes()` bumps it to now as a
 * side effect of pinning the other two. Measured end to end, two builds of one
 * recipe from separately staged trees six seconds apart: 16 differing bytes
 * before this function existed, 8 after — and all 8 sit at offset 14 of a
 * 32-byte directory entry, which is `DIR_CrtTime`. So a FAT layer is still not
 * byte-reproducible across two builds far enough apart in wall clock. Closing
 * that means rewriting the creation fields after the convert, which needs a
 * FAT directory walker — it belongs beside the other format writers in
 * `src/fs/`, not here.
 *
 * A hardlink farm is not an option for the copy: mtime is inode metadata, so
 * `Deno.utime()` through a link moves the ORIGINAL's mtime too — measured, and
 * it would mutate the caller's staging tree. Symlinks never reach here, since
 * `plan()` refuses a FAT tree that has one; one appearing after `resolve()` is
 * refused below with the rest of the drift.
 */
async function stageFatTree(
  scratch: string,
  stepId: string,
  from: DirInput,
  recorded: ResolvedInput,
  epoch: number,
): Promise<string> {
  // An entry-less resolution is not a pass. The digest in the key was taken
  // over a walk this build cannot reconstruct, so there is nothing to check
  // the tree against — and treating "unverifiable" as "matches" is the
  // silent-acceptance shape refused for the base image's size above.
  if (recorded.entries === undefined) {
    throw new Error(
      `${stepId}: the resolver recorded no entries for ${from.path}, so the ` +
        "staging tree cannot be checked against the digest its cache key " +
        "names. Resolve directory inputs with LocalInputResolver, or have " +
        "the custom resolver populate ResolvedInput.entries.",
    );
  }
  const root = await Deno.makeTempDir({ dir: scratch, prefix: "vvfat-" });
  const expected = new Map(
    recorded.entries.map((entry) => [entry.path, entry]),
  );
  const seen = new Set<string>();
  const drifted = (path: string, what: string): Error =>
    new Error(
      `${stepId}: ${path} ${what} between resolving this recipe and building ` +
        "it. The layer's key names the tree the resolver walked, so " +
        "publishing this would cache the wrong bytes under it. Re-run " +
        "resolveRecipe() after changing a staging tree.",
    );

  for await (const entry of liveEntries(from.path)) {
    const want = expected.get(entry.path);
    if (want === undefined) throw drifted(entry.path, "appeared");
    seen.add(entry.path);
    const type = entry.info.isSymlink
      ? "symlink"
      : entry.info.isDirectory
      ? "dir"
      : "file";
    if (type !== want.type) {
      throw drifted(entry.path, `changed from a ${want.type} to a ${type}`);
    }
    // The mode is in the resolver's manifest, and `plan()` derives a tree's
    // required traits from it — a file that gained the executable or setuid
    // bit after resolving is one plan() would have refused for FAT, so
    // building it anyway would drop metadata the recipe was checked against.
    if ((entry.info.mode ?? 0) !== want.mode) {
      throw drifted(
        entry.path,
        `changed mode from ${want.mode.toString(8)} to ` +
          `${(entry.info.mode ?? 0).toString(8)}`,
      );
    }
    const target = `${root}/${entry.path}`;
    if (type === "dir") {
      await Deno.mkdir(target, { recursive: true });
      continue;
    }
    if (type === "symlink") {
      // Unreachable through plan(), which refuses a FAT tree carrying one —
      // FAT has no symlinks, so vvfat would follow it and copy the target's
      // bytes in under the link's name. Refused here too rather than copied,
      // because reaching this line means the plan and the tree disagree.
      throw new Error(
        `${stepId}: ${entry.path} is a symlink, and FAT cannot represent one. ` +
          "plan() refuses a FAT staging tree containing symlinks, so this " +
          "tree is not the one that was planned. Re-run resolveRecipe() and " +
          "plan(), or replace the link with the file it points at.",
      );
    }
    await Deno.copyFile(entry.full, target);
    // The COPY, not the source: this is the byte sequence vvfat will read, so
    // it is the one whose digest has to match the key.
    const actual = await sha256Hex(await Deno.readFile(target));
    if (want.sha256 !== undefined && actual !== want.sha256) {
      throw drifted(
        entry.path,
        `changed content (recorded ${want.sha256.slice(0, 12)}, now ` +
          `${actual.slice(0, 12)})`,
      );
    }
  }
  for (const path of expected.keys()) {
    if (!seen.has(path)) throw drifted(path, "was removed");
  }

  // Deepest first, and the root last. Order is not load-bearing for mtime —
  // changing a child's timestamps does not touch its parent's — but creating
  // an entry inside a directory DOES, so every directory has to be pinned
  // after the last thing written into it.
  const pinned = vvfatLocalEpoch(epoch);
  const paths = [...expected.keys()].sort((a, b) =>
    b.split("/").length - a.split("/").length
  );
  for (const path of paths) await Deno.utime(`${root}/${path}`, pinned, pinned);
  await Deno.utime(root, pinned, pinned);
  return root;
}

/** A `raw` window onto a qcow2 layer, for splicing bytes into one partition. */
function window(imagePath: string, offset: number, size: number) {
  return {
    imageOpts: {
      driver: "raw",
      offset,
      size,
      file: {
        driver: "qcow2",
        file: { driver: "file", filename: imagePath },
      },
    },
  } as const;
}

/** Execute one `bytes` layer: the partition table, then each filesystem. */
async function runBytesLayer(
  qemu: QemuImg,
  imagePath: string,
  scratch: string,
  step: Extract<Step, { kind: "partition" }>,
  layout: readonly PlannedPartition[],
  own: readonly number[],
  resolved: ResolvedRecipe,
): Promise<void> {
  const { recipe } = resolved;
  const sectorSize = recipe.platform.sectorSize ?? 512;
  // The planner's own definition, not a second one. A `0` here — which is what
  // the special case for image bases used to produce — emits a GPT claiming a
  // zero-sector disk, with its backup header written off the front of it.
  const diskSizeBytes = totalSizeBytes(resolved);

  const partitions = await Promise.all(layout.map(async (partition) => ({
    typeGuid: typeGuidFor(partition.type, recipe.platform.arch),
    uniqueGuid: await deriveGuid(
      recipe.determinism.guidSeed,
      `partition:${partition.label}`,
    ),
    firstLba: partition.firstLba,
    lastLba: partition.lastLba,
    name: partition.label,
  })));
  const gpt = buildGpt({
    diskSizeBytes,
    sectorSize,
    diskGuid: await deriveGuid(recipe.determinism.guidSeed, "disk"),
    partitions,
  });

  // Both halves are spliced through windows, so nothing outside the GPT's own
  // footprint is touched.
  const primaryBin = `${scratch}/gpt-primary.bin`;
  const backupBin = `${scratch}/gpt-backup.bin`;
  await Deno.writeFile(primaryBin, gpt.primary);
  await Deno.writeFile(backupBin, gpt.backup);
  await qemu.convert(primaryBin, window(imagePath, 0, gpt.primary.byteLength), {
    sourceFormat: "raw",
    noCreate: true,
    parallel: 1,
  });
  await qemu.convert(
    backupBin,
    window(imagePath, gpt.backupOffsetBytes, gpt.backup.byteLength),
    { sourceFormat: "raw", noCreate: true, parallel: 1 },
  );

  for (const [index, partition] of layout.entries()) {
    // Only the windows this layer owns. The planner already divided them
    // between the host and guest layers; re-deciding here is how the two
    // halves drift apart.
    if (!own.includes(index)) continue;
    const contents = step.partitions[index].contents;
    if (contents.kind !== "fat") continue;
    // Never `contents.from.path`: qemu would read the staging tree live, at
    // build time, under a key computed from the digest the resolver took
    // earlier. See stageFatTree().
    const staged = await stageFatTree(
      scratch,
      step.id,
      contents.from,
      resolvedDir(resolved, contents.from),
      recipe.determinism.sourceDateEpoch,
    );
    // A unique name, like the staging copy above: `scratch` defaults to one
    // directory per STORE, not per build, so a fixed name would collide
    // between two concurrent builds whose recipes share a step id.
    const fatRaw = await Deno.makeTempFile({
      dir: scratch,
      prefix: "fat-",
      suffix: ".raw",
    });
    try {
      // vvfat synthesizes the filesystem from the host directory; the `raw`
      // window at 32256 strips vvfat's own MBR, so the partition type byte is
      // ours rather than vvfat's 0x06.
      //
      // Landed in a raw file rather than straight into the image window,
      // because the creation timestamps below have to be rewritten before the
      // layer is published and a qcow2 is not seekable from here. The file is
      // sparse: measured at 304 KiB written for a 504 MiB FAT16 ESP, so the
      // detour costs the directory bytes rather than the partition size.
      await qemu.convert(
        {
          imageOpts: {
            driver: "raw",
            offset: VVFAT_MBR_BYTES,
            size: partition.lengthBytes,
            file: {
              driver: "vvfat",
              dir: staged,
              "fat-type": contents.fatType,
              label: contents.label,
            },
          },
        },
        fatRaw,
        { format: "raw", parallel: 1 },
      );
      // stageFatTree() pinned mtime and atime, which settles DIR_WrtTime and
      // DIR_LstAccDate. No userspace call sets a BIRTH time, so DIR_CrtTime
      // still held the wall clock of the staging copy: measured over the
      // system smoke's recipe, two cold builds seconds apart published 8
      // differing bytes under ONE realization key, every one at offset 14 of a
      // 32-byte directory entry. That is cache poisoning, and this closes it.
      await normalizeFatTimestamps(fatRaw, {
        epochSeconds: recipe.determinism.sourceDateEpoch,
      });
      await qemu.convert(
        fatRaw,
        window(imagePath, partition.offsetBytes, partition.lengthBytes),
        { sourceFormat: "raw", noCreate: true, parallel: 1 },
      );
    } finally {
      // A snapshot is a full copy of the ESP tree, so leaving it behind would
      // grow the store's scratch by one ESP per built layer.
      await Deno.remove(staged, { recursive: true }).catch(() => {});
      await Deno.remove(fatRaw).catch(() => {});
    }
  }
}

/** The 1-based partition number a `run` or `copyIn` step mounts as root. */
function rootPartitionNumber(plan: Plan, resolved: ResolvedRecipe): number {
  const base = resolved.recipe.base;
  // An existing image brings its own table, so the recipe has to name the
  // partition; a recipe that declares its own layout is unambiguous by
  // construction, because plan() refuses more than one ext4 window.
  if (base.kind === "image") return base.rootPartition;
  const index = (plan.layout ?? []).findIndex((p) => p.filesystem === "ext4");
  if (index < 0) {
    throw new Error(
      "no ext4 partition in the plan to mount as root — plan() should have " +
        "refused this recipe before build() ever saw it",
    );
  }
  return index + 1;
}

/** The shell script a guest layer runs, and any tar it needs alongside it. */
async function guestWork(
  step: PlannedStep,
  plan: Plan,
  resolved: ResolvedRecipe,
): Promise<{ script: string; data?: Uint8Array }> {
  const { recipe } = resolved;
  const sectorSize = recipe.platform.sectorSize ?? 512;
  const declared = recipe.steps[step.index];

  if (step.id.endsWith(":mkfs")) {
    const layout = plan.layout ?? [];
    const partitionStep = declared as Extract<Step, { kind: "partition" }>;
    const partitions: MkfsPartition[] = [];
    for (const index of step.partitionIndices ?? []) {
      const geometry = layout[index];
      const contents = partitionStep.partitions[index].contents;
      // The GPT partition NAME and the ext4 volume label are different
      // strings that both live in `label`; conflating them writes one into
      // the other's field, where it is valid and wrong.
      const fsLabel = contents.kind === "ext4" ? contents.label : "";
      partitions.push({
        number: index + 1,
        // sysfs reports start and size in 512-byte units ALWAYS, whatever the
        // device's logical block size is.
        startSectors512: geometry.firstLba * sectorSize / 512,
        sizeSectors512: geometry.lengthBytes / 512,
        fsLabel,
        uuid: await deriveGuid(
          recipe.determinism.fsSeed,
          `fs:${geometry.label}`,
        ),
        hashSeed: await deriveGuid(
          recipe.determinism.fsSeed,
          `hash:${geometry.label}`,
        ),
      });
    }
    return {
      script: mkfsScript({
        fakeTimeEpoch: recipe.determinism.sourceDateEpoch,
        partitions,
      }),
    };
  }

  const rootPartition = rootPartitionNumber(plan, resolved);
  if (declared.kind === "run") {
    return {
      script: runScript({
        rootPartitionNumber: rootPartition,
        script: declared.script,
      }),
    };
  }
  if (declared.kind === "copyIn") {
    return {
      script: copyInScript({
        rootPartitionNumber: rootPartition,
        to: declared.to,
      }),
      data: await tarOf(declared, resolved),
    };
  }
  throw new Error(`step ${step.id} has no guest work to do`);
}

/**
 * Build the ustar blob a `copyIn` step delivers.
 *
 * Every file is re-hashed against the digest the resolver recorded. A tree
 * edited between `resolve()` and `build()` would otherwise be archived as-is
 * under a key naming what it used to hold — a cache entry that is wrong from
 * the moment it is written.
 */
async function tarOf(
  step: Extract<Step, { kind: "copyIn" }>,
  resolved: ResolvedRecipe,
): Promise<Uint8Array> {
  const input = resolvedDir(resolved, step.from);
  const mtime = resolved.recipe.determinism.sourceDateEpoch;
  const entries: TarEntry[] = [];
  for (const entry of input.entries ?? []) {
    if (entry.type === "dir") {
      entries.push({ path: entry.path, type: "dir", mode: entry.mode, mtime });
      continue;
    }
    if (entry.type === "symlink") {
      entries.push({
        path: entry.path,
        type: "symlink",
        mode: entry.mode,
        mtime,
        // Passed through undefined rather than defaulted to "": buildTar()
        // refuses a symlink with no target, because an empty linkname
        // extracts as a dangling link. `?? ""` satisfied the guard's letter
        // and produced exactly the link it exists to prevent.
        linkTarget: entry.linkTarget,
      });
      continue;
    }
    const body = await Deno.readFile(`${step.from.path}/${entry.path}`);
    const actual = await sha256Hex(body);
    if (entry.sha256 !== undefined && actual !== entry.sha256) {
      throw new Error(
        `${step.id}: ${entry.path} changed between resolving this recipe and ` +
          `building it (recorded ${entry.sha256.slice(0, 12)}, now ` +
          `${actual.slice(0, 12)}). The layer's key names the recorded ` +
          "content, so publishing this would cache the wrong bytes under it.",
      );
    }
    entries.push({
      path: entry.path,
      type: "file",
      mode: entry.mode,
      mtime,
      body,
    });
  }
  return buildTar(entries);
}

/**
 * Execute a plan, reusing cached layers.
 *
 * Refuses a plan that needs the guest appliance unless one is wired in — with
 * a typed error naming the requirement rather than silently skipping the step.
 */
export async function build(
  plan: Plan,
  resolved: ResolvedRecipe,
  options: BuildOptions,
): Promise<Artifact> {
  const qemu = options.qemu ?? new QemuImg();
  const sectorSize = resolved.recipe.platform.sectorSize ?? 512;
  const store = options.store;
  const scratch = options.scratch ?? `${store.root}/scratch`;
  await Deno.mkdir(scratch, { recursive: true });
  await Deno.mkdir(`${store.root}/layers`, { recursive: true });

  const layers: StoredLayer[] = [];
  const cacheHits: RealizationKey[] = [];
  let parent: StoredLayer | undefined;

  for (const step of plan.steps) {
    if (step.executor === "guest" && options.guest === undefined) {
      throw new GuestExecutorUnavailableError(
        step.id,
        "this step needs a Linux kernel (ext4 creation, or running target " +
          "ELF), which no host-side mechanism can provide",
      );
    }
    const key = await realizationKey(
      step.recipeKey,
      parent === undefined ? undefined : {
        realizationKey: parent.realizationKey,
        contentSha256: parent.contentSha256,
      },
    );

    const cached = step.cacheable
      ? await store.get(key, { trust: options.trustCache })
      : undefined;
    if (cached !== undefined) {
      cacheHits.push(cached.realizationKey);
      layers.push(cached);
      parent = cached;
      continue;
    }

    const dir = await store.begin(key);
    let published: StoredLayer;
    try {
      const imagePath = `${dir}/image.qcow2`;
      if (parent === undefined) {
        const base = resolved.recipe.base;
        if (base.kind === "image") {
          const info = await qemu.info(base.from.path, { format: base.format });
          // An absent `virtual-size` is not a pass. It means the one check
          // standing between a recipe and a base image it was not written
          // against could not run, and treating "unknown" as "matches" is the
          // silent-acceptance shape this package refuses everywhere else.
          if (info.virtualSizeBytes === undefined) {
            throw new Error(
              `qemu-img info reported no virtual size for ${base.from.path} ` +
                `(format ${base.format}). The declared virtualSizeBytes ` +
                "cannot be checked against it, so the base is refused rather " +
                "than accepted unverified. Confirm the format is the image's " +
                "real one.",
            );
          }
          if (info.virtualSizeBytes !== base.virtualSizeBytes) {
            throw new BaseImageSizeMismatchError(
              base.from.path,
              base.virtualSizeBytes,
              info.virtualSizeBytes,
            );
          }
          // Copied in, never referenced as a backing file. A backing reference
          // would bake an absolute host path into a store layer and destroy
          // the relocatability the store promises — and would leave the
          // layer's content at the mercy of a file outside the store.
          await qemu.convert(base.from.path, imagePath, {
            sourceFormat: base.format,
            format: "qcow2",
            parallel: 1,
          });
        } else {
          await qemu.create(imagePath, {
            format: "qcow2",
            size: base.sizeBytes,
            ...(base.options === undefined ? {} : { options: base.options }),
          });
        }
      } else {
        // Relative, so the whole store stays relocatable — and resolvable from
        // the same-depth `.partial` sibling both before and after the rename.
        await qemu.create(imagePath, {
          format: "qcow2",
          backing: `../${parent.realizationKey}/image.qcow2`,
          backingFormat: "qcow2",
        });
      }

      if (step.executor === "bytes") {
        const declared = resolved.recipe.steps[step.index];
        if (declared?.kind === "partition" && plan.layout !== undefined) {
          await runBytesLayer(
            qemu,
            imagePath,
            scratch,
            declared,
            plan.layout,
            step.partitionIndices ?? plan.layout.map((_, i) => i),
            resolved,
          );
        }
      } else if (step.executor === "guest") {
        const { script, data } = await guestWork(step, plan, resolved);
        const declared = resolved.recipe.steps[step.index];
        const result = await options.guest!.run({
          stepId: step.id,
          // The layer's own `.partial`, opened read-write. Never a published
          // parent: qemu would open that read-write too, and every descendant
          // already cached against it would be reading different bytes.
          imagePath,
          script,
          nonce: await stepNonce(key, step.id),
          scratchDir: dir,
          ...(data === undefined ? {} : { data }),
          ...(declared?.kind === "run" && declared.network === true
            ? { network: true }
            : {}),
          ...(sectorSize === 4096 ? { sectorSize } : {}),
        });
        // Four independent signals, because the guest's own exit code answers
        // only the first of them: a step can return 0 over a filesystem that
        // failed to unmount, that e2fsck rejects, or that the kernel logged I/O
        // errors against. Any one of them means the layer must not be published.
        const { outcome } = result;
        if (
          outcome.code !== 0 || outcome.umountRc !== 0 ||
          (outcome.fsckRc ?? 0) !== 0 || outcome.dmesgErrors !== 0
        ) {
          throw new GuestStepFailedError(step.id, outcome, result.console);
        }
      }

      // Digested from the `.partial` image, through its whole backing chain —
      // this is the layer's identity, and every descendant's key folds it.
      // Cheap despite the flattening: the materialization it reads through is
      // sparse, so it costs the allocated bytes, not the virtual size.
      published = await store.publish(
        key,
        step.recipeKey,
        await contentDigest(qemu, imagePath, { scratch, format: "qcow2" }),
        parent === undefined ? undefined : {
          contentSha256: parent.contentSha256,
          realizationKey: parent.realizationKey,
        },
      );
    } catch (error) {
      // A failed layer must leave nothing a later build could mistake for
      // progress, and must not keep holding the key's lock. The `.partial`
      // directory can hold a half-written filesystem — publishing is the only
      // thing that ever renames it into place, so it was never reachable, but
      // it would sit there and the lock would stay held in this process.
      await store.abandon(key);
      throw error;
    }
    layers.push(published);
    parent = published;
  }

  if (parent === undefined) throw new Error("plan produced no layers");
  // Materialize by flattening the chain, so the artifact stands alone.
  await qemu.convert(parent.path, options.output, {
    format: "qcow2",
    parallel: 1,
  });
  return {
    path: options.output,
    realizationKey: parent.realizationKey,
    layers,
    cacheHits,
  };
}

/** Re-export for callers wiring their own store. */
export { LayerStore };
export type { PlannedStep };
