/**
 * `build()` — execute a {@linkcode Plan} as a chain of qcow2 overlays.
 *
 * Each layer is created backed by its parent and published into the
 * content-addressed store, so re-running a build after editing one step
 * rebuilds only from that step onward.
 *
 * Two mechanisms do all the work. `image` and `bytes` layers use `qemu-img`
 * alone: a `raw` node with `offset`/`size` is a *window* onto the layer, so a
 * partition table or a filesystem is spliced in without touching its
 * neighbours, and FAT comes from qemu's `vvfat` driver reading a host
 * directory. `guest` layers boot the build appliance.
 *
 * @module
 */

import { QemuImg } from "../qemu_img.ts";
import { buildGpt, deriveGuid, PARTITION_TYPE_GUIDS } from "../fs/gpt.ts";
import { buildTar, type TarEntry } from "../fs/tar.ts";
import {
  copyInScript,
  type GuestRunner,
  type GuestStepResult,
  type MkfsPartition,
  mkfsScript,
  runScript,
  stepNonce,
} from "../system/mod.ts";
import { sha256Hex } from "../digest.ts";
import { contentDigest } from "./content.ts";
import { type RealizationKey, realizationKey } from "./keys.ts";
import {
  type Plan,
  type PlannedPartition,
  type PlannedStep,
  totalSizeBytes,
} from "./plan.ts";
import { LayerStore, type StoredLayer } from "./store.ts";
import { GuestExecutorUnavailableError } from "./errors.ts";
import { resolvedDir } from "./resolve.ts";
import type { ResolvedRecipe, Step } from "./types.ts";

/** vvfat's own MBR occupies the first 32256 bytes; a window past it is the
 * bare filesystem. */
const VVFAT_MBR_BYTES = 32256;

/** Options for {@linkcode build}. */
export interface BuildOptions {
  /** Where layers are cached. */
  readonly store: LayerStore;
  /** Destination for the final artifact. */
  readonly output: string;
  /** The driver. @default a new QemuImg */
  readonly qemu?: QemuImg;
  /** Skip the on-hit container digest check. @default false */
  readonly trustCache?: boolean;
  /** Scratch directory for generated byte blobs. @default alongside the store */
  readonly scratch?: string;
  /**
   * Where `guest` layers run. Omit and a plan containing one is refused with
   * {@linkcode GuestExecutorUnavailableError} rather than skipped — but every
   * layer BEFORE it still builds, publishes and caches.
   */
  readonly guest?: GuestRunner;
}

/** A guest step ran, and either it or the filesystem under it failed. */
export class GuestStepFailedError extends Error {
  /** The offending step's id. */
  readonly stepId: string;
  /** Everything the guest reported. */
  readonly outcome: GuestStepResult["outcome"];
  /** The guest's serial console, for diagnosis. */
  readonly console: string;

  /** Build the error, naming which of the four signals actually failed. */
  constructor(stepId: string, result: GuestStepResult) {
    const { outcome } = result;
    const reasons = [
      outcome.code !== 0 ? `the script exited ${outcome.code}` : "",
      outcome.umountRc !== 0 ? "a filesystem failed to unmount" : "",
      (outcome.fsckRc ?? 0) !== 0 ? `e2fsck exited ${outcome.fsckRc}` : "",
      outcome.dmesgErrors !== 0
        ? `the kernel logged ${outcome.dmesgErrors} I/O or ext4 errors`
        : "",
    ].filter((reason) => reason !== "");
    super(
      `${stepId}: ${reasons.join(", ")} (stage ${outcome.stage}). The layer ` +
        "was NOT published, so nothing downstream can cache against it.\n" +
        result.console.split("\n").slice(-20).join("\n"),
    );
    this.name = "GuestStepFailedError";
    this.stepId = stepId;
    this.outcome = outcome;
    this.console = result.console;
  }
}

/** What a build produced. */
export interface Artifact {
  /** Path to the materialized image. */
  readonly path: string;
  /** The final layer's realization key. */
  readonly realizationKey: RealizationKey;
  /** Per-layer provenance, base first. */
  readonly layers: readonly StoredLayer[];
  /** Which layers were served from cache. */
  readonly cacheHits: readonly string[];
}

/** Map a recipe partition type to its spec GUID. */
function typeGuidFor(type: string, arch: string): string {
  if (type === "esp") return PARTITION_TYPE_GUIDS.esp;
  if (type === "linux-root") {
    return arch === "aarch64"
      ? PARTITION_TYPE_GUIDS["linux-root-aarch64"]
      : PARTITION_TYPE_GUIDS["linux-root-x86_64"];
  }
  return PARTITION_TYPE_GUIDS["linux-generic"];
}

/** A `raw` window onto a qcow2 layer, for splicing bytes into one partition. */
function window(imagePath: string, offset: number, size: number) {
  return {
    imageOpts: {
      driver: "raw",
      offset,
      size,
      file: {
        driver: "qcow2",
        file: { driver: "file", filename: imagePath },
      },
    },
  } as const;
}

/** Execute one `bytes` layer: the partition table, then each filesystem. */
async function runBytesLayer(
  qemu: QemuImg,
  imagePath: string,
  scratch: string,
  step: Extract<Step, { kind: "partition" }>,
  layout: readonly PlannedPartition[],
  own: readonly number[],
  resolved: ResolvedRecipe,
): Promise<void> {
  const { recipe } = resolved;
  const sectorSize = recipe.platform.sectorSize ?? 512;
  // The planner's own definition, not a second one. A `0` here — which is what
  // the special case for image bases used to produce — emits a GPT claiming a
  // zero-sector disk, with its backup header written off the front of it.
  const diskSizeBytes = totalSizeBytes(resolved);

  const partitions = await Promise.all(layout.map(async (partition) => ({
    typeGuid: typeGuidFor(partition.type, recipe.platform.arch),
    uniqueGuid: await deriveGuid(
      recipe.determinism.guidSeed,
      `partition:${partition.label}`,
    ),
    firstLba: partition.firstLba,
    lastLba: partition.lastLba,
    name: partition.label,
  })));
  const gpt = buildGpt({
    diskSizeBytes,
    sectorSize,
    diskGuid: await deriveGuid(recipe.determinism.guidSeed, "disk"),
    partitions,
  });

  // Both halves are spliced through windows, so nothing outside the GPT's own
  // footprint is touched.
  const primaryBin = `${scratch}/gpt-primary.bin`;
  const backupBin = `${scratch}/gpt-backup.bin`;
  await Deno.writeFile(primaryBin, gpt.primary);
  await Deno.writeFile(backupBin, gpt.backup);
  await qemu.convert(primaryBin, window(imagePath, 0, gpt.primary.byteLength), {
    sourceFormat: "raw",
    noCreate: true,
    parallel: 1,
  });
  await qemu.convert(
    backupBin,
    window(imagePath, gpt.backupOffsetBytes, gpt.backup.byteLength),
    { sourceFormat: "raw", noCreate: true, parallel: 1 },
  );

  for (const [index, partition] of layout.entries()) {
    // Only the windows this layer owns. The planner already divided them
    // between the host and guest layers; re-deciding here is how the two
    // halves drift apart.
    if (!own.includes(index)) continue;
    const contents = step.partitions[index].contents;
    if (contents.kind !== "fat") continue;
    // vvfat synthesizes the filesystem from the host directory; the `raw`
    // window at 32256 strips vvfat's own MBR, so the partition type byte is
    // ours rather than vvfat's 0x06.
    await qemu.convert(
      {
        imageOpts: {
          driver: "raw",
          offset: VVFAT_MBR_BYTES,
          size: partition.lengthBytes,
          file: {
            driver: "vvfat",
            dir: contents.from.path,
            "fat-type": contents.fatType,
            label: contents.label,
          },
        },
      },
      window(imagePath, partition.offsetBytes, partition.lengthBytes),
      { noCreate: true, parallel: 1 },
    );
  }
}

/** The 1-based partition number a `run` or `copyIn` step mounts as root. */
function rootPartitionNumber(plan: Plan, resolved: ResolvedRecipe): number {
  const base = resolved.recipe.base;
  // An existing image brings its own table, so the recipe has to name the
  // partition; a recipe that declares its own layout is unambiguous by
  // construction, because plan() refuses more than one ext4 window.
  if (base.kind === "image") return base.rootPartition;
  const index = (plan.layout ?? []).findIndex((p) => p.filesystem === "ext4");
  if (index < 0) {
    throw new Error(
      "no ext4 partition in the plan to mount as root — plan() should have " +
        "refused this recipe before build() ever saw it",
    );
  }
  return index + 1;
}

/** The shell script a guest layer runs, and any tar it needs alongside it. */
async function guestWork(
  step: PlannedStep,
  plan: Plan,
  resolved: ResolvedRecipe,
): Promise<{ script: string; data?: Uint8Array }> {
  const { recipe } = resolved;
  const sectorSize = recipe.platform.sectorSize ?? 512;
  const declared = recipe.steps[step.index];

  if (step.id.endsWith(":mkfs")) {
    const layout = plan.layout ?? [];
    const partitionStep = declared as Extract<Step, { kind: "partition" }>;
    const partitions: MkfsPartition[] = [];
    for (const index of step.partitionIndices ?? []) {
      const geometry = layout[index];
      const contents = partitionStep.partitions[index].contents;
      // The GPT partition NAME and the ext4 volume label are different
      // strings that both live in `label`; conflating them writes one into
      // the other's field, where it is valid and wrong.
      const fsLabel = contents.kind === "ext4" ? contents.label : "";
      partitions.push({
        number: index + 1,
        // sysfs reports start and size in 512-byte units ALWAYS, whatever the
        // device's logical block size is.
        startSectors512: geometry.firstLba * sectorSize / 512,
        sizeSectors512: geometry.lengthBytes / 512,
        fsLabel,
        uuid: await deriveGuid(
          recipe.determinism.fsSeed,
          `fs:${geometry.label}`,
        ),
        hashSeed: await deriveGuid(
          recipe.determinism.fsSeed,
          `hash:${geometry.label}`,
        ),
      });
    }
    return {
      script: mkfsScript({
        fakeTimeEpoch: recipe.determinism.sourceDateEpoch,
        partitions,
      }),
    };
  }

  const rootPartition = rootPartitionNumber(plan, resolved);
  if (declared.kind === "run") {
    return {
      script: runScript({
        rootPartitionNumber: rootPartition,
        script: declared.script,
      }),
    };
  }
  if (declared.kind === "copyIn") {
    return {
      script: copyInScript({
        rootPartitionNumber: rootPartition,
        to: declared.to,
      }),
      data: await tarOf(declared, resolved),
    };
  }
  throw new Error(`step ${step.id} has no guest work to do`);
}

/**
 * Build the ustar blob a `copyIn` step delivers.
 *
 * Every file is re-hashed against the digest the resolver recorded. A tree
 * edited between `resolve()` and `build()` would otherwise be archived as-is
 * under a key naming what it used to hold — a cache entry that is wrong from
 * the moment it is written.
 */
async function tarOf(
  step: Extract<Step, { kind: "copyIn" }>,
  resolved: ResolvedRecipe,
): Promise<Uint8Array> {
  const input = resolvedDir(resolved, step.from);
  const mtime = resolved.recipe.determinism.sourceDateEpoch;
  const entries: TarEntry[] = [];
  for (const entry of input.entries ?? []) {
    if (entry.type === "dir") {
      entries.push({ path: entry.path, type: "dir", mode: entry.mode, mtime });
      continue;
    }
    if (entry.type === "symlink") {
      entries.push({
        path: entry.path,
        type: "symlink",
        mode: entry.mode,
        mtime,
        linkTarget: entry.linkTarget ?? "",
      });
      continue;
    }
    const body = await Deno.readFile(`${step.from.path}/${entry.path}`);
    const actual = await sha256Hex(body);
    if (entry.sha256 !== undefined && actual !== entry.sha256) {
      throw new Error(
        `${step.id}: ${entry.path} changed between resolving this recipe and ` +
          `building it (recorded ${entry.sha256.slice(0, 12)}, now ` +
          `${actual.slice(0, 12)}). The layer's key names the recorded ` +
          "content, so publishing this would cache the wrong bytes under it.",
      );
    }
    entries.push({
      path: entry.path,
      type: "file",
      mode: entry.mode,
      mtime,
      body,
    });
  }
  return buildTar(entries);
}

/**
 * Execute a plan, reusing cached layers.
 *
 * Refuses a plan that needs the guest appliance unless one is wired in — with
 * a typed error naming the requirement rather than silently skipping the step.
 */
export async function build(
  plan: Plan,
  resolved: ResolvedRecipe,
  options: BuildOptions,
): Promise<Artifact> {
  const qemu = options.qemu ?? new QemuImg();
  const sectorSize = resolved.recipe.platform.sectorSize ?? 512;
  const store = options.store;
  const scratch = options.scratch ?? `${store.root}/scratch`;
  await Deno.mkdir(scratch, { recursive: true });
  await Deno.mkdir(`${store.root}/layers`, { recursive: true });

  const layers: StoredLayer[] = [];
  const cacheHits: string[] = [];
  let parent: StoredLayer | undefined;

  for (const step of plan.steps) {
    if (step.executor === "guest" && options.guest === undefined) {
      throw new GuestExecutorUnavailableError(
        step.id,
        "this step needs a Linux kernel (ext4 creation, or running target " +
          "ELF), which no host-side mechanism can provide",
      );
    }
    const key = await realizationKey(
      step.recipeKey,
      parent === undefined ? undefined : {
        realizationKey: parent.realizationKey,
        contentSha256: parent.contentSha256,
      },
    );

    const cached = step.cacheable
      ? await store.get(key, { trust: options.trustCache })
      : undefined;
    if (cached !== undefined) {
      cacheHits.push(step.id);
      layers.push(cached);
      parent = cached;
      continue;
    }

    const dir = await store.begin(key);
    let published: StoredLayer;
    try {
      const imagePath = `${dir}/image.qcow2`;
      if (parent === undefined) {
        const base = resolved.recipe.base;
        if (base.kind === "image") {
          const info = await qemu.info(base.from.path, { format: base.format });
          if (info.virtualSizeBytes !== base.virtualSizeBytes) {
            throw new Error(
              `base image ${base.from.path} has a virtual size of ` +
                `${info.virtualSizeBytes} bytes; the recipe declares ` +
                `${base.virtualSizeBytes}. Every partition LBA and the backup ` +
                "GPT's position derive from that number, so planning against " +
                "the wrong one lays out a disk that is not this one.",
            );
          }
          // Copied in, never referenced as a backing file. A backing reference
          // would bake an absolute host path into a store layer and destroy the
          // relocatability the store promises — and would leave the layer's
          // content at the mercy of a file outside the store.
          await qemu.convert(base.from.path, imagePath, {
            sourceFormat: base.format,
            format: "qcow2",
            parallel: 1,
          });
        } else {
          await qemu.create(imagePath, {
            format: "qcow2",
            size: base.sizeBytes,
            ...(base.options === undefined ? {} : { options: base.options }),
          });
        }
      } else {
        // Relative, so the whole store stays relocatable — and resolvable from
        // the same-depth `.partial` sibling both before and after the rename.
        await qemu.create(imagePath, {
          format: "qcow2",
          backing: `../${parent.realizationKey}/image.qcow2`,
          backingFormat: "qcow2",
        });
      }

      if (step.executor === "bytes") {
        const declared = resolved.recipe.steps[step.index];
        if (declared?.kind === "partition" && plan.layout !== undefined) {
          await runBytesLayer(
            qemu,
            imagePath,
            scratch,
            declared,
            plan.layout,
            step.partitionIndices ?? plan.layout.map((_, i) => i),
            resolved,
          );
        }
      } else if (step.executor === "guest") {
        const { script, data } = await guestWork(step, plan, resolved);
        const declared = resolved.recipe.steps[step.index];
        const result = await options.guest!.run({
          stepId: step.id,
          // The layer's own `.partial`, opened read-write. Never a published
          // parent: qemu would open that read-write too, and every descendant
          // already cached against it would be reading different bytes.
          imagePath,
          script,
          nonce: await stepNonce(key, step.id),
          scratchDir: dir,
          ...(data === undefined ? {} : { data }),
          ...(declared?.kind === "run" && declared.network === true
            ? { network: true }
            : {}),
          ...(sectorSize === 4096 ? { sectorSize } : {}),
        });
        // Four independent signals, because the guest's own exit code answers
        // only the first of them: a step can return 0 over a filesystem that
        // failed to unmount, that e2fsck rejects, or that the kernel logged I/O
        // errors against. Any one of them means the layer must not be published.
        const { outcome } = result;
        if (
          outcome.code !== 0 || outcome.umountRc !== 0 ||
          (outcome.fsckRc ?? 0) !== 0 || outcome.dmesgErrors !== 0
        ) {
          throw new GuestStepFailedError(step.id, result);
        }
      }

      // Digested from the `.partial` image, through its whole backing chain —
      // this is the layer's identity, and every descendant's key folds it.
      // Cheap despite the flattening: the materialization it reads through is
      // sparse, so it costs the allocated bytes, not the virtual size.
      published = await store.publish(
        key,
        step.recipeKey,
        await contentDigest(qemu, imagePath, { scratch, format: "qcow2" }),
        parent === undefined ? undefined : {
          contentSha256: parent.contentSha256,
          realizationKey: parent.realizationKey,
        },
      );
    } catch (error) {
      // A failed layer must leave nothing a later build could mistake for
      // progress, and must not keep holding the key's lock. The `.partial`
      // directory can hold a half-written filesystem — publishing is the only
      // thing that ever renames it into place, so it was never reachable, but
      // it would sit there and the lock would stay held in this process.
      await store.abandon(key);
      throw error;
    }
    layers.push(published);
    parent = published;
  }

  if (parent === undefined) throw new Error("plan produced no layers");
  // Materialize by flattening the chain, so the artifact stands alone.
  await qemu.convert(parent.path, options.output, {
    format: "qcow2",
    parallel: 1,
  });
  return {
    path: options.output,
    realizationKey: parent.realizationKey,
    layers,
    cacheHits,
  };
}

/** Re-export for callers wiring their own store. */
export { LayerStore };
export type { PlannedStep };
